(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib._lib = function() {
	this.initialize();

}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


// symbols:
(lib.Bullet = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF33").s().p("AAhgBIAAAAQAAgCAAgCQAAgIABgEQAHgaAJAAQAIAAAHAaQAAACABAFQAAADABAFQgDALAAAFQgFgRAAAAIgBAAQgDAbgBAMQAAgFgIgiIgBAAIgBAXIgIgbIAAAAQgCADgBADIAAAAAgEhMQgCANAAAFQgFgTAAAAIgBAAQgDAdgBAMQAAgFgIgkIgBAAIgBAZIgIgdIgBAAQgBADgCAEQABgMABgFQAHgaAJAAQAIAAAGAaQABACABAFQAAADAAAFIAAAAAggBNQgCANAAAGQgFgTAAgBIgBAAQgDAdgBANQAAgGgIgjIgBAAIgBAZIgIgdIgBAAQgBADgCAEQABgNABgFQAHgZAJAAQAIAAAGAZQABADABAEQAAAEAAAEIAAAA").cp();
	this.shape.setTransform(0,-8.2,0.6,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC00").s().p("ABCgeQACAQAAAcIgEAOIgdAAQAAgCgEgMQAAgWABgPQAAgBAAAAQAAgCAAgCQAAAAABgBQABgDABgDIABAAIAIAdIABgZIABAAQAIAiAAAFQABgLADgcIABAAQAAAAAFATQAAgGACgMIAAAAAgmhmQACgEABgDIABAAIAIAdIABgZIABAAQAIAkAAAFQABgNADgcIABAAQAAAAAFATQAAgGACgMQACAQAAAeIgEAOIgdAAQAAgCgEgMQAAgZABgPQAAgCAAgCIAAAAAhCA0QACgEABgDIABAAIAIAdIABgZIABAAQAIAjAAAGQABgNADgdIABAAQAAABAFATQAAgGACgNQACAQAAAfIgEAOIgdAAQAAgCgEgMQAAgZABgPQAAgDAAgBIAAAA").cp();
	this.shape_1.setTransform(0,-6.5,0.6,0.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FEFDAB","#FFFF00","#FFCC00"],[0,0.235,1],0.7,-3.6,0.9,4.9).s().p("AAAAAQAAAAAAAAIAAAAQAAAAAAAAIAAAA").cp();
	this.shape_2.setTransform(1.9,-8.3,0.6,0.6);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.1,-15.3,8.2,15.4);


(lib.Background = function() {
	this.initialize();

	// Layer 1
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#99CCFF","#026FDB"],[0.11,1],0.8,-6.1,3.3,46.7).s().p("Ar7i9QDGC/A+AAQAwAABagrQBagtAtAAQDoCAAaAAQBThYBUhaQggBBgIAKIAAAZQAfgUB3hUQBWg9ALAAQABAAAYAiQAcAlAUAOQBUA8AQAAQAFgKACglQACglgEgVIAAg8QAoAeBTAYQAnALAuAMQBlBiAJAAQALAAAegdQASgSAtgwQANgNAMgLQgMASAFALIAeAAQAwgOACgBIAeAAQABAFABAfQAIAdAtAAQAqAAAcgeQANgOAFgLQA4A3AnAAQAEAACXhgQAJgGALgHQAwgfA+goIAIAFIAAABQgXAjgrA7IAAAKQAUAAEEh4QgFBDAnAzQAgAqAxAUQAFg3AAiHQAIAAB6BGQAjAQAXABQAOABAhgCQACABABABQBtBSA9AAQAiAABXhOIACABQgBAAAAABQgPAVAAAPIAZAAQAMgGAxgSQAqgPAHgGQADAHgDAXQAEAUAkAAQAKAAAUgMQAUgNAFAAQADAAAGAEQADACACACQAIAFAHACIAABGQgKABgKAAQnWAhm8CSQm1i2ncBnQnLBlm1CzQlziVmKhMQnMhZnTAYQnOAbmKDyQh6gbh8gSIAAmKIAAgKQAjgWAwggQATgMAQgLIAFAHQgOAQABASIAZAAQBxgnAvgLIAAAZQgFAKgGAfQgGAdgIAKIAABGIAAADQACACAIAAQAQAABDhSQBChTANAAQAHAAA7AnQA9ApAkAFIAoAAQAFgFAAgMQAAgPgdgtQgUgfgHgPQALAHAKAHQABAAABABIACgDIAAAAQAEgCAEgCQAEADAFADQABAAABABQADACAEACQCGBUBRAAQAXAAAqgfIAFAGQgIAIgWAUQgQATAGASQCogoACAAQAAAAAsArQA0AoAngNQgOgNgNgeQgOgggEgKIAZAAQAiAPAfAAQAAgBABgBQBIAqA0AAQAyAAB1haQAFgDAFgEIAGAEIAAABQgYAjgsA+IABAFQATgCC5hYQALAXBGAtQBJAvAkAAQAFgPAAgMQAAgZgUgmQgJgSgGgMIAEgFQASACAeAKQASAGAYAKQAkAOAeAFIAAAA").cp();
	this.shape_3.setTransform(277,302.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#A9E34F").s().p("Az5hEQGJjyHOgbQHSgaHMBbQGJBMF2CVQnRC4njB0QjTAyjTApQi2gzivhTQmNi7mohbIAAAA").cp();
	this.shape_4.setTransform(152.2,336.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#97DE29").s().p("A41E7QDWgpDSgxQHkh1HQi3QGzizHLhmQHchoG1C4QhPAahPAeQoYDNojCvQo6C6pYApQmMAgl0hoIAAAA").cp();
	this.shape_5.setTransform(301.5,339);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#66CC00").s().p("AcrlnQG8iUHWghQAKAAAKgBIAAQ7MhWhAAAIAAr+QB8ASB6AbQGpBdGMC5QCwBTC1AzQF0BnGMgfQJWgqI8i5QIjivIYjOQBPgeBPgaIAAAA").cp();
	this.shape_6.setTransform(277,347.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#DDEEFF").s().p("ASqA4QACACACADQAKAKAKAKQgFAKgNAPQgcAegqAAQgtAAgIgeQgBgfgBgEIgeAAQgCAAgwAPIgeAAQgFgLAMgTQBJhEAmAAQATAFAWAHQAfAPAnApIAAAAAZTg4QCIhXBDgpQADACADADQAEAEAFAEQAgAeBSBNQAEADAEAEIAAgHQAMAAAMACQAeACAnAZQAhAUAuADQAXARAVAQQghACgOAAQgXgBgjgQQh6hEgIAAQAACFgFA3QgxgVgggpQgng0AFhAQkEB2gUAAIAAgKQArg6AXgjIABAAQAAgBABgBQAGgKAFgHIAAAAACMBWQAYgZAXgZQAHgIAIgHQAGgHAGgGQBohsA1gyQADACADACQA3AuBbBbQABABABABIAAgCIAAAAQAgAFAzAKQAmAIAcAFQAhAhAaAaQgugNgngLQhTgYgogdIAAA8QAEAUgCAlQgCAlgFALQgQAAhUg8QgUgOgcglQgYgigBAAQgLAAhWA9Qh3BUgfAUIAAgZQAIgLAghAIAAAAEAmnAAcQACgDAEgEQAKgKAKgIQAtgnAWgTQACABACACQADgCADgDIAAgHQAIgHABgBQAKAMAVAbQASAVALAAQACAAAmgiQADgDADgDQACgCADgCQAAgBAAAAQAJgIALgKIAACHQgHgBgIgGQgCgCgDgBQgGgEgDAAQgFAAgUAMQgUANgKAAQgkAAgEgUQADgXgDgHQgHAGgqAPQgxARgMAHIgZAAQAAgQAPgVQAAAAABgBIAAAAA5mgCQAHADAHAFQAWAPAUAMQgBACAAABQgfAAgigPIgZAAQAEAJAOAgQANAeAOAOQgnANg0gpQgsgqAAAAQgCAAioAoQgGgTAQgTQAWgTAIgIIgFgGQAGgFAHgEQAFgEAFgEIABAAQAYgWAYgLQADABADACQACABABABIAAgCIABAAQABAAACABQAYADApAVQAhAQATAEQALADAGAAQAUAAAVgIIAAAAAxeiJQAOALARAQQAIAHBbBZQAEAEAEAEIAAAAIACgCQAGAKAJASQAUAnAAAYQAAANgFAPQgkAAhJgwQhGgtgLgUQi5BWgTACIgBgFQAsg+AYgiIABAAQAAgBABgBQAIgMAGgIQAGgFAGgFQBQhDAcgUQAIgFAHgEQADADADADIAAAAEgmegCfQAHAFAJAGQAbATBEAwQACABACABQAEAEAEADQAQAKAPAKQABABABAAIACgDQAggQAXgJQABAAABAAQAEAEAEADQAFADAFADQAHAPAUAfQAdArAAAPQAAANgFAFIgoAAQgkgFg9gpQg7glgHAAQgNAAhCBQQhDBTgQAAQgIAAgCgDIAAgCIAAhGQAIgLAGgcQAGgeAFgJIAAgZQgvALhxAlIgZAAQgBgQAOgQQABgCABgBQABAAAAgBQAKgMAGgIQAtgeATgMQBSg0A/gVQAFACAFAEIAAAA").cp();
	this.shape_7.setTransform(282.5,279.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#99CCFF").s().p("Aa5gWIgBgBIgHgFQACgBACgBQAIgGAJgGQgFAIgGAKQgBAAAAACIgBAAEAogAAjQgEAEgDAEIgBgCQAEgDAEgDIAAAAAyIAAIgBgBIgGgEQABgCABAAQAKgIAKgIQgGAJgIAMQAAAAgBABIAAABEgofgATIABAAQAMgKAMgGQgGAIgKAMQgBAAAAABQgCAAgBACIgFgH").cp();
	this.shape_8.setTransform(271.1,278.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CCE6FF").s().p("AWTAsQgJgJgKgLQgCgCgCgCIAFgGQAUAOAAAGQAAAFgCAFIAAAAA1XgdIgCAFQAAABAAABQAAAOgDAHQgVgMgWgQQgHgFgGgEQAFgDAGgCIAAAAQASAIANADQAKADAHAAQABAAABAAIAAAA").cp();
	this.shape_9.setTransform(261.6,283.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6192DA").s().p("ATVgrQgLAGgJAHQiXBegEAAQgoAAg4g3QACgGAAgDQAAgGgUgNIgFAFQgngpgggRQAOAEAQAEQCdAqAMgTQABAAACABQALAAANgBQAqAIATgCQAbACAGgHQAAAAACAAQATAAAYgDIAAAAANAhUQgnAAhJBGQgMAMgNALQgsAvgSASQgeAegLAAQgKAAhkhiQgbgYghghQAmAHAQAAQALAAARgFQAGgBAHgCQACABADAAQAmAHAQAAQAEAAAFgBQAHABAFAAQAdAABagjQAigNAagIQAIACAJADQARAFAWAGIAAAAEAizgC7QAYALAYASQANAKAZAVQgWATguApQgJAIgLAKQgDADgEADQhYBNghAAQg9AAhthRQgCgBgBgBQgWgQgXgTQAGAAAHAAQAWAAATgGQACgBACAAQAUAGAWABQAGAAAHAAQAEAAAFAAQAGAAAFAAQAnAAAhgTQATgLAigeQAmgiAmgPQAHADAHADIAAAAEAkogCzQAQAJAPAMQANAKAZAVQABABADACQACgBABgCQACgBABgBIAAgHQAGAGAJAGQgEADgDADQgmAigBAAQgMAAgRgVQgVgbgKgMQgCABgHAHIAAgzIAAgCQAKAEAKAGQAAAAAAAAIABAAA39hcQgEAEgFAEQh2BYgyAAQg0AAhHgpQADgHAAgOQAAgBAAAAIACgFQAFAAAFgBQAFABADAAQAkAAAngeQAKgIALgGQAGACAGACQAKACAKADQAPAEAOADQABgBABAAQAJgIAKgHQAAgBABAAQABgBACgCQAGACAIACQAOAEASAFQAPAEAOADQABgBABAAQABgBACgCQAIACAHACIAAAAAh/g6QANAEARAAQADAAAEgBQAHABAHAAQAIAAAbgHQACAAADgBQgGAGgGAHQgHAHgHAIQgYAZgXAXQhVBahSBaQgaAAjqiCQgtAAhaAtQhaAtgxAAQg+AAjGi/QASADARAAQALAAAhgEQAFgBAGAAQAFABAFABQASADARAAQADAAAGgBQAGABAFAAQATAABTgLQALACANAEQAcAIAjAMQBkAhAnAAQAYAAAXgEQAGgBAGgBQAZAGAQAAQAHAAAGAAQAEAAAEAAQBUAABjgwQAdgPAYgKQAHACAIACQAJABAJAAQAIAAAbgHQADAAADgBQAEgEADgEQABAAAAABQAHAGALAEQACAAABABIAAAAEghmgBBQgqAfgXAAQhRAAiGhVQgDgCgEgCIACgDQAYgMATgIQAGADAFACQAPAHAQAKQBAAlAnADIABAAQAPgNAOgJQAEABADACQAlARAaACIABAAQABgCACgBQAJACAIABQgFAEgGAFQgGAFgHAFIAAAA").cp();
	this.shape_10.setTransform(307.7,287.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#BCEBFE","#0260EC"],[0,0.859],3.7,179.6,2.3,-118.1).s().p("AdmSYQgDgDgDgDQhEAqiHBWQgJAGgJAGQgBABgCABQg+AogxAfQgXAEgTgBQgCAAgBAAQgFAHgbgCQgTACgqgHQgNAAgMAAQgXgGgcgHQgQgFgOgEQgWgGgSgGQghgJgXgHQgwgOgCAAQgUAAghAJQgJgDgIgCQgaAIgiANQhaAjgdAAQgFAAgHAAQgFAAgEAAQgQAAgmgGQgDgBgCAAQgHABgGACQgNgDgPgDQgzgLgfgFIgBAAIAAABQAAAAgBgBQhghgg4guQgzgqgSAAQgHAAgnAkQgDgCgCgCQg1AyhpBvQgDAAgCABQgbAGgIAAQgHAAgHAAQgEAAgDAAQgRAAgNgEQgBAAAAgBQAAAAgBAAQgLgPgCAAQgaAAgvATQgIgCgHgCQgYALgdAOQhhAyhUAAQgEAAgEAAQgGAAgHAAQgQAAgZgFQgGABgGAAQgdgIglgNQgzgRgkgJQglgJgWAAQgUADgRACQgNgDgLgDQhTALgTAAQgFAAgGAAQgGAAgDAAQgRAAgSgDQgFgBgFgBQgGABgFAAQgMgEgMgEQgYgKgTgHQgegKgRgBIgGAGIgBAAQgEgDgDgEQhchZgHgHQgVgUgRgNQgkgegNAAQgYAAgoAZQgEgDgDgCQgHAEgHAFQgdAUhQBCQgGAFgGAFQgKAIgKAIQgBAAgBACQgHgCgIgCQgCABgBABQgBAAgBACQgOgEgPgEQgSgFgOgEQgIgBgGgCQgCABgBABQgBAAgBABQgWgGAAAAQgYAAgXAKQgGgCgGgCQgLAGgKAIQgnAegkAAQgDAAgFgBQgFABgFAAQgBAAgBAAQgHAAgKgDQgNgDgSgIIgBAAQAAgBgBAAQgrgVgZgDIAAAAIAAABQgCgBgBAAQgEgCgDgCQgggRgZAAQgYAAgaALQgBAAgCAAIAAAAIAAABQgCgBgBAAQgEgCgDgCQgXAMgZAVIAAAAQgIAAgJgCQgCABgBABIgBAAQgagCglgRQgKgFgKgGQgXgNgTgIQgngTgYAAQgLAAgVAIQgHACgHAEQgGgDgFgCQgTAHgYANIgCACQgBAAgBAAQgEgDgFgDQgEABgEADIAAAAQgCgBgCgCQgFgDgFgDQgFgDgEgDQAAAAgBgBQgBgBgCgBQhDgvgbgTQgPgLgLgHQgcgRgJAAQggAAgqANQgFgDgEgDQg/AWhSA0QgUAMgsAeQgMAHgMAJIgBAAQgQALgTAMQgvAggkAWIAAAKQAAAAAAAAMAAAgshMBWNAAAMAAAAqzQgCACgDADQgIgHgHgFIAAAHQgBAAgBABQgQgNgJgIQgZgTgagLIgBAAQAAgBgBAAQgKgGgKgEIAAADQgZgIgaAAQgWAAgXAHQgGgDgHgDQgmAPgmAiQgjAfgSAKQghATgnAAQgGAAgFAAQgFAAgFAAQgGAAgGAAQgXgBgTgGQgCABgCAAQgGgDgGgEQgogZgegCQgMgBgLAAIgBAGQgEgEgDgDQhThNgggeQgIgGgGgHQgsgmgLAAQgEAAg3AiIAAAA").cp();
	this.shape_11.setTransform(276,144.3);

	this.addChild(this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,554,401.5);


(lib.Airplane = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{explode:5},true);

	// timeline functions:
	this.frame_9 = function() {
		this.parent.removeChild(this);
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9));

	// Layer 1
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#CCCCCC").s().p("AgmgLQgDgBgDAAIALgJQAAABgBACQgBAEgDADIAAAAAAKAYQgBAAAAgBQgEgFAHgKQAGgGADgCQADAAAEgCQAJgFAGABQACAAACAAQAAACAAADQAAAIgKAIQgCACgHADQgCACgDABQgEABgEABQgDAAgCgBIAAAAAgogYIgGAGIAAABIAAgGQAEgBACAAIAAAA").cp();
	this.shape_12.setTransform(-7.1,7.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#9D9D9D").s().p("AA8gIQgCAAgCAAQgGgBgJAFQgEACgDACQgDAAgGAGQgHAKAEAGIAAAAQgBAAAAgBQAAgBgBgBQgEgFAHgKQAGgEADgCQADgCAEgCQAJgFAGABQAEAAACACIAAAAAgrgNQgBAAgBAAQgDAAgDABQAHAFAIADQgCABgDABQgIACgEAAQgEAAgBAAQgBgBAAgDQAAgGAGgFQAGgEADgCIABAAIAAAI").cp();
	this.shape_13.setTransform(-8.4,7.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AgbgBQgGABgGADQgKAEgOgDQgKgCADgIQACgIAGgFQAIgHAKgEIABAJQgBABAAAAQgDABgGAFQgGAEAAAGQAAAEABAAQABAAAEAAQAEAAAIgCQADgBACgBQAEABAFACIAAAAAAHAFQACgCABgCQABgBAAAAQADgCADgEQACgBACgBQACgCABgBQADgCAEgCQABAAABgBQALgFAKAAQACAAABAAIABAAQADAAADABQAAABABAAIABABQAEADABAGQACAJgHAJQgEAHgHAFQgDADgFACQgEACgEACQgJACgMgCQgBAAgBAAQgLgDgCgGQgBgBABgCQAAgGAEgHIAAAAAAWAWQAAAAABAAQACACADgBQAEAAAEgCQADgBACgBQAHgDACgCQAKgJAAgIQAAgCAAgCQgCgCgEgBQgGAAgJAEQgEACgDADQgDABgGAFQgHAKAEAFQABABAAAAQAAABABAAIAAAA").cp();
	this.shape_14.setTransform(-8.4,7.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#9E9FBE").s().p("Ag3gNQACAAADABIAAAVIAAAAQgBAAgCABIgBgIIAAgBIgBgHIAAgHAArABIALgIQABABABABIgJAGQgCAAgCAAIAAAAAAPgKIgBAVQgCABgCACIACgYIABAAQABAAABAAIAAAAAgrADIAGgFIAIgHQABAAACAAIgRAOIAAgC").cp();
	this.shape_15.setTransform(-7.4,5.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#3E3F5B").s().p("AgkADQgDAAgCgBIgBgJQADABACAAQAFABAFABIgBAJQgFgBgDgBIAAAAAgEAHQgDAAgFAAQgCgBgBAAIAAgBIAKgHQACAAADAAQACABAFAAIgLAIAApAFQgEAAgIAAQgBAAgBAAIgBAAIABgFQABAAACAAQAGAAAHAAIgCAF").cp();
	this.shape_16.setTransform(-8.8,3.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#66FF00").s().p("AAPgNQAEABAFABQAKADANACQgQADgaAFQgbAIgGAEQgHgDgKgGQAGgDAcgHQAQgGAKgCIAAAA").cp();
	this.shape_17.setTransform(-11.3,-5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#33CC00","#002B00"],[0,1],-0.5,-2,0.9,2.2).s().p("AhKAFQAUABACgJQABgDAAgDQACgCAFgDQAEgDAGAAQAHAAADABQAAAAAEADQAHADAQAAQAJAAANgBQAMgBADAAQADAAAKABQAJABAEAAQAHAAACgBQAAAHgEAFIAAABQgTABgPADQABABABAAQACAEADAEQABACABABQgFAAgEAAQgCAAgDAAQgHAAgGgBQgBAAgCAAQgLAAgHgBQgEAAgFAAQgDAAgCgBQgFAAgFgBQgGAAgFgBQgFgBgFAAQgDgBgCAAQgKgCgGgCQgDgBgDgBIAAAA").cp();
	this.shape_18.setTransform(-7.7,1.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.rf(["#FFFFC4","#FFFF00","#FF9900"],[0.024,0.408,0.757],-1.2,-0.6,0,-1.2,-0.6,8.2).s().p("AAhAPQAAADgBADQgCALgUgBQgKgEgHgEQgZgOAAgQQAAgLARgMIABAAQAJAAAIAEQAJAFAIAIQAOANgBAPIAAAA").cp();
	this.shape_19.setTransform(-16.3,-1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["#33CC00","#002B00"],[0,1],-1.5,-3,1.7,6).s().p("AgRgkQABACAKAEQgKACgSAGQgcAJgGADQAKAGAHADQAGgFAdgIQAYgGAQgDQANACAQABIABAAQAaAUAHAaQABAEAAAFIAAABQgDABgGAAQgEAAgKgCQgJgBgDAAQgDAAgNABQgMACgJAAQgQAAgHgEQgEgCAAgBQgEgBgGAAQgGAAgEAEQgFADgCABQABgPgOgPQgIgHgJgEQgKgEgJAAQAMgJAUgIQARgHAVgEIAAAA").cp();
	this.shape_20.setTransform(-9,-3.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#33CC00","#002B00"],[0,1],-0.7,-1,0.7,1.1).s().p("AASAGIgDgDQgMACgKABQAAgHgOgEQAKgBAGAAQACAAACAAQAGAAAGABQAJABABACQADADgGAFIAAAA").cp();
	this.shape_21.setTransform(31.9,-3.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFCC00").s().p("ADsgwQgLACgWACQgdADgHABQgEgCgEgCQgCgBgBgBIABAAQAQgBARgBQAIgBAHgBQAMgBAMgCIADADQACABACABIAAAAAiKAHQgDgEgCgDQgBAAAAAAQAPgCASgCQABAAAAABQABAAAAgBIAAAAQAKgBAKAAQAggCAvABQACAEAEACQgMAAgLAAQgkAAgkABQgTACgIABQgIABgEACIAAAAAjdAlQADABADAAQAEABAEABQAEABAFABQAFABAFABQABAAAQABQgEAEgCADQgBABAAABQgIgBgIgCQgXgEgSgJQABAAABAAQACAAABAAIAAAAQADgBACAAQACAAABAAQABAAAAAAIAAAA").cp();
	this.shape_22.setTransform(10.5,2.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FF9900").s().p("AC1hQQAAACgGAAQgCAAgGABQgMADgDABQgPAFgMAJQgKAIgGAKQgGAJgBAIQgDAAgDAAQAAgIAGgKQAHgKAKgIQAMgJAOgFQAEgBAMgDQACgBACAAQABAAABAAQAAgBABAAQADAAACAAQAEAAAEAAIAAAAAiTBRQgBAAAAAAIAAAAIAAgBQABgFAjgEQAjgDApAAQABAAAGAAQABAAAAAAIABAAIAAABIgBAAQgHAAgBAAQgpAAgiADQgjAEgBAFQAAAAAAAAIAAAAAgyAvIAAAAQgYgBgKAAQgbAAgfADQggADgFAFIAAABQAAAAAAAAQgBAAAAgBIAAAAQAGgGAggDQAfgDAbAAQAKAAAXABIABAAIAAAB").cp();
	this.shape_23.setTransform(15.9,-1.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FF6600").s().p("AAbgaQgCABgDABQgMADgEABQgMAFgMAJQgKAGgGAKQgGAJgBAJQgBAAgCAAQAAgHAGgLQAIgNAPgIQAQgJAQgEQAFgBAFgBIAAAAAAtgbIgeA1QgHAAgIAAQgNABgUAAQgBABAAAAQAAgJAGgJQAGgKALgFQALgJANgFQAEgBAMgDQAFgCADAAQAGAAAAgCIAAAAQABAAABAAIAAAA").cp();
	this.shape_24.setTransform(29.7,-6.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.lf(["#33CC00","#002B00"],[0,1],-0.5,-0.9,0.1,0.8).s().p("AAWgKQAGADAIADQgSAEgVAEQgPAEgRADQAHgEADgHIAAAAQACAAACAAQABgBADgDQAFgFAJgBQACAAAMABQAGAAAFgBIAAAA").cp();
	this.shape_25.setTransform(25.7,-0.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.lf(["#33CC00","#002B00"],[0,1],-2.1,-1.6,-0.1,1.9).s().p("AgMgPQACAAABAAQAEAAADAAQAAAAABAAQASgBAOgBQAOAFAAAJQgHABgIAAQgRACgPAAIAAAAQABAAABABQADABADADQAEABAEABQgEABgHAAQgMgBgCAAQgJACgFAFQgCACgCABQgBAAgCABQAAgEAAgFQAAgIgDgGQgBgBgBgBIBGgFIgIgDIhCADQgBgBgCgBQAOAAASgBIAAAA").cp();
	this.shape_26.setTransform(26.5,-2.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#33CC00").s().p("AAAAAQAAAAACACIhHADIgGgFIBLAAAAAgBIBEgDIAIADIhHADQgCgCgDgBIAAAA").cp();
	this.shape_27.setTransform(22.2,-3.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.lf(["#33CC00","#002B00"],[0,1],-0.2,-1.5,0.9,1.7).s().p("AhGAGQAFgHAAgIQADAAAKACQAFACAHAAQAHAAAJgCQAKgBAEAAQACAAAOACQAQADAOAAQAPAAAKgGQADgBAEgCQACgBABAAQgBAJgEAHQgBAEgCACQgBAAABABQgIACgJABQgGAAgFABQgCgBgBgCQgDgDgDgDQgsgCghACQgKAAgJABIAAAA").cp();
	this.shape_28.setTransform(6.7,1.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.lf(["#33CC00","#002B00"],[0,1],-0.3,-1.2,0.4,1).s().p("AgvAOQACgDACgDQADgIABgJIAKABQAIABAGAAQAGAAAJgDQALgDAEAAQAEAAALABQALACAEAAQACAAABAAQgDAHgIADIAAAAIAAAAQgmAIguAGIAAAA").cp();
	this.shape_29.setTransform(18,0.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.lf(["#33CC00","#002B00"],[0,1],-1.8,-1.6,0.3,2.8).s().p("AAigRQABAAAAABQACAAABABIhJABIAGAGIBHgCQABABABAAQAEAIAAAGQAAAFgBAEIgBAAQgBAAgBAAQgEAAgLgBQgMgCgDAAQgEAAgKADQgLAEgGAAQgGAAgIgCIgJAAIAAgBQABgPgIgRQAYACAkgBQAIAAANgBIAAAA").cp();
	this.shape_30.setTransform(18.2,-2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#006600").s().p("AAqAMQgBAKgDAJQgCADgCAEIAAAAQgBAAAAAAQAAAAgBAAQgBgBABAAQACgDABgDQAEgJABgKIAAAAQABgPgIgRIABgBQAAAAABAAQAAAAAAABIABAAQAIARgCAPIAAAAAB4AYIAAgBIAAAAQAIgEADgIIAAAAQABgEAAgFQAAgGgEgIQgBgBAAgBQgCgDgDgBQgBgBgBAAQgBgBgBAAQAAgBABAAIABAAQABAAABAAQABACACAAQACACACADQABABAAABQAEAIAAAGQAAAFgBAEIAAAAQgDAIgHAEQgBAAgBABQAAAAgBAAIAAAAAhgARQAAAIgFAJIAAAAQgBABAAAAQgBgBAAAAIAAAAQAEgHAAgHIAAgBQABgFgBgEQgHgYgbgXIAAAAQAAAAABAAIAAAAQABAAAAAAIAAAAQAbAXAHAXQAAADABAFIAAAA").cp();
	this.shape_31.setTransform(9.8,-1.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#CC0000").s().p("AgPgGQAFgEAIgBQAGgBAHAEQAHADACAFQABADgFAEQgFAEgIABQgHAAgGgDQgHgDgCgFQgBgDAFgEIAAAA").cp();
	this.shape_32.setTransform(6.3,-2.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgGgxQgEgDgFgDQAMgBAKACQAEAAAEABIAAACIgCABQgCAAgBAAQgJAAgHABIAAAAAAWARQAJgIAQgBQAQgBANAGQANAHADAJQACAKgJAIQgJAHgRACQgQABgMgGQgOgHgCgJQgDgKAKgIIAAAAAAkAYQgFAEACAFQABAFAHAEQAHADAIgBQAIAAAFgEQAFgEgBgFQgBgGgHgDQgHgDgIABQgJAAgFAEIAAAAAgrgnQgHgEgJgBQALgEALgDQAEgBAEgBQAGADAFADQgCABgCAAQgLADgKAEIAAAAAhIglQAJABAHAEQgHAFgFAGQgBABgCAAQgJADgLgEQABgBACgCQAHgHAJgGIAAAA").cp();
	this.shape_33.setTransform(0.9,-5.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.lf(["#33CC00","#002B00"],[0,1],-1.4,-3,1.6,5.8).s().p("AgyAiQgBgEAAgEQgHgZgbgUQAFAAAFAAQBCADAagHQARgFABgGQAAgCgBgDQADABACAAQALADAPAOQAMAMACAGIAAAAQAIAPgBARIAAABQgCAAgBABQgFACgCABQgKAGgPAAQgOAAgQgDQgQgCgCAAQgDAAgJABQgJACgHAAQgHAAgFgCQgKgCgDAAIAAAAAgTgCQgJAFADAKQACAKANAGQALAGAQgBQAQgBAJgIQAKgHgDgKQgCgIgOgGQgMgGgQABQgOABgKAIIAAAA").cp();
	this.shape_34.setTransform(5.2,-3.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#7B8FE1").s().p("AAjAMQAOgJAEgKQAFADACADQAAAAAAABIAAAAQAAAAAAABIAAACQAAABgBABQgBADgNADQgFABgFAAIAAAAAAsgKQgCAMgRALQgJAAgKABQAIgOgIgMQAEgBAFAAQARAAAMADIAAAAAgcANQABgMgFgHQANgEAOgBQAHALgEAOQgMAAgOgBIAAAAAg3AMQgEgBAAgDQAAgFANgEQAIAGgBAIQgIAAgIgBIAAAA").cp();
	this.shape_35.setTransform(0.9,-7.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFF00").s().p("AiWguIAAAAQAAAAgBAAIAAAAQgBAAAAAAQgQgBgOgCQgMgCgLgCQgFgCgEgBQgKgDAAgDQAAgCACgCQADgDAMgCIABAAQgCADAAADIAAAAQABACAPADQAMACARABIAAAAQAIABAIAAQAEAAAEAAQABAAACAAQAOABAMAAQAFAAAFAAQAKgBAJAAQAFAAAFgBQAFAAAFgBQANgDABgDQABgBAAgBIAAgCQAAgCAAAAIAAgBQAAgBAAAAQAAgBAAgBQAMABAEAGQABABAAABQABACAAADQgBAGgRAEQgcAHhCgCQgFgBgFAAIAAAAADDghIAeg3QANAAAGAEQAFADAAAIQAAAIgVATQgJAIgGAFQgGAAgIAAQgCAAgCAAIAAAAACbgKQAHAAAdgDQAWgDALgBQAHAEAGADQACACADAAQAGADAGACQgSADgUACQgLACgKgBIgTgEQgHgDgHgDQgEgBgDgCIAAAAAiKAxQgEgEgEgEQgCgCgBgBQADgCAJgBQAHgCATgBQAlgDAjAAQALAAAMAAQABACABABQADADACADQgXgBgKAAQgbAAgfADQggAEgGAFIAAAAAgIAnQAFAGADADQAFAHAGAFQgGAAgBAAQgnAAgjAEQgiAEgCAFQgLgHgLgJQAAAAAAAAIgBAAQgCgCgCgCQgBgBgCgBQAAAAAAgBIAAAAQAEgFAhgEQAegDAbAAQAKAAAYABIAAAAAAMA9QAIAGAIAFQgRADgbACQgeADgUAAQgUAAgKgBQgCgBgDgCQgCgBgCgBQABAAAAgBQAAgEAjgEQAigEAnAAQABAAAHAAIAAAAAjBBZQgGgCAAAAQgGgBgEgBQgLgCgJgDQgFgBgEgBQgIgDgHgFQADgBADAAQASAJAYAEQAHABAIABQgBACgCADIAAAA").cp();
	this.shape_36.setTransform(11.7,-0.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#99CCFF").s().p("ABKAEQACgGgDgJQAEAEACAFQACACAAAEIAAAAQAAABAAABIAAABQAAABAAABQgCgDgFgCIAAAAAgzgJQAQgJATgDQACABACAAQADACABABQgDABgEAAQgMADgKAEQgDAAgEAAQgEAAgDAAIAAAAAgLAFQgCgDgCgCQgEgBgDgCQAKgFAMgCQAAgBABAAQAJAGAEAFQgOABgLAEIAAAAAg/gBQACgBAFAAQACAAADAAQgJAEgHAIQgBABgCACQALAEAJgDQACgBABgBQAFgGAHgEQAEACADADQACABABACQgNAFAAAGQAAACADACQgQgBgNgDQgOgCgCgCIAAgBQAAgCACgDIAAgBQABAAAAgBQACgCACgCQAEgEAGgCIAAAAAAEgTQgBgBgCgBQgBgBgBgBQADgBAFAAQAiAAAUAGQAGALgCAIQgMgBgRAAQgFAAgEAAQgEgHgJgGQAJgCAIABQACAAACAAIACgBIAAgDQgEAAgEgBQgMgBgNABIAAAA").cp();
	this.shape_37.setTransform(-1.1,-9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#666699").s().p("AANA2QACACADACIgIAFQgCgBgEAAIAAgBIAJgHAgrhUQADgDAFgCQACgBACgBQADgBAEAAQAEAAACABQAJABAHAEQACACACADQADACABADQAGAJgBAMQgCAAgCAAQgEAAgDAAQAAgIgFgIQgBgBgCgCQgDgDgEgCQgHgEgJgBQgDgBgCAAQgFAAgCABIAAAAAAihRQgFgHgIgGQgFgDgGgDQgCgBgCgBQgCgBgCgBQAFgBAGAAQABgBACAAQACACADABQABABACAAQAFADAEADQAJAHAEAHQAIANgIAPQgFAAgFAAQAGgPgIgMIAAAAABBg3QARgLADgOQABgJgGgLQACABADABQAFACACACQAEAJgDAIQgDAMgPAJQgFABgFAAIAAAAAgOAwIgGAUQgEACgDACIABgYQAIAAAEAAIAAAAAg9AyIgNAKIgKAJQAAgBgBAAQgBAAgCABQgCAAgDAAIAAgXQADABAFABIAAAAIgBAKIgBAGIABgBIAAACIARgPQAFAAADAAIAAAAAgdBqQAAABAAAAQAAAAgBgBIABAA").cp();
	this.shape_38.setTransform(-3.1,-0.8);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgZhiQgCgDgFgCQgDgBgCgBQgUgGghAAQgGAAgFABQgCAAgBAAQgGABgFABQgTADgQAJQgCABgCABQgFADgDADQgGAEgEAEQgCACgCACQAAABgBAAIAAABIAAgBQgMACgDADQgCACgBADQgVAEgRAHQgUAIgMAJIgBAAQgRAMAAALQAAAQAZAOQAJAEAKAEQADABADABQAGACAJACIABALIAAAHQgKAEgHAHQgHAFgCAIQgDAKAKACQAPADAKgEQAGgDAFgDQAJADALACQAFABAFABQABAAAGABQgEAHgBAGQAAACAAABQACAGALADQACAAABAAQALACAKgCQAEgCAEgCQAEgCADgDQAHgFAEgHQAHgKgBgKQgCgGgEgDIgBgBQAAAAgBgBIAIgFIAAAAQAAABABAAQALAJAKAGIAAABIABAAQAAAAABAAQACACACABQACABACABQAKABAUAAQAVAAAbgCQAegCARgEQgIgEgIgGIAAAAIAAgBIAAAAQgBAAAAAAQgHgGgGgGQgEgEgEgFIAAgBIgBAAQgDgDgCgDQAFgBAGgBQAJgBAIgBQABAAAAAAQAAAAABAAIAAAAQAugHAogHIAAAAQABAAAAAAQABgBABAAQARgDAPgEQAXgDASgFIASAFQALAAALAAQAUgBASgFQgGgDgHgCQgCgBgCgBQgGgEgHgEQgCgBgCgBQAFgFgCgFQgBgCgKgBQAHgFAJgIQAVgTAAgJQAAgHgGgDQgFgEgNAAQgBAAgBAAIAAAAIgBAAQgEAAgEAAQgCAAgCAAQgBAAgBABQAAAAgBAAQgFABgFABQgQADgSAJQgPAIgIAPQgGALAAAHQgTABgNABQgBAAgBAAIgBAAQAAAAAAAAQgNABgIAAQgmABgYgCIgBAAQAAAAAAAAQgBAAAAAAQgCgGgNgMQgPgOgKgDQgCAAgCgBQAAgBAAgBQgEgFgNgCIAAgBQAAgBAAgBIAAAAQAAgFgBgDQgCgFgFgEIAAAAAgWhtQAOAGAFAMQABADABAFQAIADAEAFQAOADASARQAJAJAEAGQAVABAegBQAHAAAMgBQAKAAANgBQACgGAEgHQAJgRASgJQAUgLASgEQAQgDARAAIACAAQAWAAAJAGQAIAFAAALQABAKgYAVQgDAEgDACQADADAAACQADAFgDAFQAFAEAGADIAAAAIAAAAQAIADAHADQAEACABACQABADgCACQgCADgFAAQgUAEgWADQgNABgOgBQgEAAgCgBIgLgDQgPAEgSAEQgSADgSAEQAAAAgBAAQgpAIguAGIAAAAQAAABgBAAQgGAAgGABQAEAEADADQAMAOAPAIQAEACAAADQAAADgDACQgCACgFABQgSADgfADQgdACgWAAQgVAAgLgBQgGAAgDgCQgDgCgCgBQAAAAgBgBQgBAHgFAIQgFAIgIAGQgEADgFADQgFADgGACQgQAFgTgFQgCAAgBAAQgTgFgDgJQgBgDABgCQAAgEABgEQgBAAgCgBQgGgBgGgBQgCABgDABQgPAHgYgFIgBAAQgWgCAGgSQADgKAIgGQAGgGAJgFIgBgJQgFgBgEgBIAAAAQgDgBgEgCQgLgEgJgFQgdgQAAgTQgBgNAVgPIAAAAQAOgKAVgIQAQgHATgEQABgBACgCQADgEAOgDQABgBABgBQAFgFAGgFQAEgDAFgDQAbgQAggDQABAAABAAIABAAQAHgBAGAAQAoAAAWAIQAEABADABIAAAAAiLA/IAGgUIACgGQACAAADAAQAEAAAFAAQAEAEAFAFIAAAAQAAABAAAAQABAAAAAAQAAAAABAAIgLAKQgKAAgLAFQgBABAAAAIAAAAAiUAsIgCAaQgBABgCABQgQgBgBAAQgFgBgFgBQgFgBgEgBQgEgBgEgBQACgDACgEQAAgBAAgBIANgKIANgLQAJABALAAIgBAIAimA/QABAAAAAAIACgQIgEADQAAACAAACQgBAEgCAEQACABACAAIAAAAAi1AiIgKAKIAAABIgIAHQgDAAgDABIABgJIAAgBIABgLQAGABAGAAQAFABAFAAIAAAAAjYA5IAAABIgBAAQABAAAAgBIAAAA").cp();
	this.shape_39.setTransform(8.7,-0.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f().s("#333333").ss(1,1,1).p("AhHApQgCgWgMgTQgKgTgQgNAAKAxQALgVgMgVQgBgBgCgCAA1gjIgDAOIA+gDAAygVIgDALIA5gBAA4gwIgDANIA7gDAAvgKIgDAK");
	this.shape_40.setTransform(21.6,-5.5);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.lf(["#06A5E8","#00121A"],[0,0.859],-1.6,0,1.7,0).s().p("AgOgWIAAAAQAOAFARAEQAAABAAABQAAANgFAKQgFAJgGACQAAAAgBAAIAAAAQgFAAgFgJQAAgBgBgBQgEgKAAgNQAAgGABgFIAAAA").cp();
	this.shape_41.setTransform(-16.2,4.4);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.lf(["#BCEBFE","#279CE9"],[0,0.863],-0.2,1.8,0.4,-1.6).s().p("AAmgOQgIALgBAMQgRACgZADQgNACgLABQAXgNAFgOQABgDABgDIAAAAQAHAAAHABQAOABARAAIAAAA").cp();
	this.shape_42.setTransform(-7.4,5.6);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.rf(["#FFC4C4","#FF0000"],[0,0.435],-0.7,-0.4,0,-0.7,-0.4,6.7).s().p("AgCgaIAAAAQANAAAIAKQAGAHAAAGQAAAHgGAJQAAABgBABQgJAMgOAAQgCAAgBAAQgRgNAAgQQAAgIAUgOQACgBABgBIAAAA").cp();
	this.shape_43.setTransform(-20,-2.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.lf(["#06A5E8","#00121A"],[0,0.859],-1.6,0,1.7,0).s().p("AARAAQAAAOgFAKQgFAJgFACQgBAAgBAAIAAAAQgFAAgFgJQAAgBgBgBQgFgKABgOQgBgDABgEQABgJADgHQABgBAAgBQACgDACgCQADgDADgBQAAAAACABQADAAACADQACACADAFQACAEABAGQACAGAAAHIAAAA").cp();
	this.shape_44.setTransform(-1.3,7.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.lf(["#BCEBFE","#279CE9"],[0,0.863],2.3,-2.4,1.5,4.8).s().p("AgTAWQgjgCgcgGQgSgEgOgFQAAAAgBAAQgHgDgGgCQgLgDgHgGQACAAACAAQAQAAAJgMQAEAAAJgBQAOgBAHAAQALAAAHADIAKAIQAIAFAJACQAOAEAXAAQAigCAFAAQANAAAJACQAGABAHAAQAIADAGABQAJACAMAAQAWAAAOgDQABAAACAAQgCAEgEAFQgBABgBABQgRgBgUgBQgVgCgZgBQgDAAgEAAQgNABgJAMQgBABAAABQgRAAgMgBQgIAAgIgBIAAAA").cp();
	this.shape_45.setTransform(-6.2,1.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.lf(["#BCEBFE","#279CE9"],[0,0.863],1,2.3,-1.1,-2.6).s().p("AhSAqQAXgNAFgQQAIgXgUgVQgGgFgHgFIABAAQAUABARABQgBACgBABQAFAGBBAAQACgBACgBQAJABAGABQAQADALAJQAKAHgBAFQgCAYhJANQgNACg1AGQgMACgLABIAAAA").cp();
	this.shape_46.setTransform(12,7);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.lf(["#BCEBFE","#279CE9"],[0,0.863],-1.2,-2.4,2.2,3.8).s().p("AgUAfQgFgEgPgGQALgVgNgTQgBgBgBgCQATgCASgCQASgCAUgCQAEAAADABQAHACAAAIQAAACAAADIgCAAQgKgCgIgCQgWACgSAEQgGABgFABQAHAGAPADQAQACAOAAIABAAQAEAAAEAAQgCACgCACQgCACgEADQgJAGgPAGQgJAFgMAEIAAAA").cp();
	this.shape_47.setTransform(26.8,-2.7);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFCC33").s().p("AA5gTIADgMIA5gBIg5ABIADgLIA+gDIg+ADIADgOIADgNQANgDAPAAQADAAADABQASADAEAJQABACAAACQABAFgCAFQgCAHgGAGQgGAFgIAFQgDgBgEAAQgTACgUACIAAAAAh8BAQAAgBACgBQADgFACgEQAXAEAUABQASACARAAQABAAAAAAQADAAAEAAQgFADgIAEQgDACgDACQgCABgCABQhDAAgFgGQABgBABgCIAAAAABCg4IA7gDIg7AD").cp();
	this.shape_48.setTransform(20.3,-3.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.lf(["#BCEBFE","#279CE9"],[0,0.863],-0.1,-1.2,1.9,7.1).s().p("AAjgBQAKAAAJgBQACABABABQAMAUgLAVIgBAAQgTgIgNgCQgaABgWABQgCgWgMgTQgKgTgQgNQA3AQATAYQAMAAAMgBIAAAA").cp();
	this.shape_49.setTransform(16.8,-4.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FF0000").s().p("AC7hIIgCAMQgTADgTACQgJAAgKABQAAgFAAgDQABgNAMgKQAJgJAQgHQAPgGAQgDIgDAOIgDANIgEALADjgeQgDAAgEAAIAAAAQgPAAgSgFQgPgDgHgGQAFgBAGAAQAUgFAWgCQAIACAKACQABAAAAABQABAAABAAQAXAFAHACQgEAEgSAEQgKABgKABIAAAAACXgKQAPAFAFAEQAFABAAACQAAAHgoAGQgZADgRABQgDAAgDAAQgBAAgBAAQgQAAgSgBQgVgCgWgDQgCgBgBAAQgGgBgGgBQgMgCgMgDQgYgFgUgEQgDgCAAgBIAAgBQAAgCAIAAQA8gFAjgCQASgBAXgBQAXgBAbAAQAOACATAIIABAAAh3A7QABgOAIgLQAAgBABgBQAJgNANgBQAEAAADAAQAZACAVABIAAABQAHAFAFAFQAVAVgIAYQgFARgXANQggADgLABQgCAAgBAAQgBAAAAAAQgPAAgKgNQgKgOAAgTQAAgDAAgDIAAAAAjcAYQAcAFAjADQgBADgBADQgFAQgXANQggAEgLABQgBAAgCAAQAAAAgBAAQgOAAgKgOQgKgNAAgUQAAgIACgIQAGADAHACIAAABQgBAFAAAGQAAAOAFAKQAAABABABQAFAJAGAAIABAAQABAAAAAAQAGgCAEgJQAFgKAAgOQAAgBAAgBIAAAAAhGBBQAAgIgCgGQgBgGgCgEQgDgFgCgCQgCgDgDAAQgCgBgCAAQgDABgDADQgCACgCADQAAABgBABQgDAHgBAJQgBAEABAEQgBAPAFAKQABABAAABQAFAIAGAAIABAAQABAAABAAQAFgBAFgJQAFgKAAgPIAAAA").cp();
	this.shape_50.setTransform(7.5,0.6);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AALgWQAFAAAFAAQAZAAAdADQAUACATADQhEgGgEAAQgDAAgLABQgFAAgDAAQgBAAgBAAQgEgCgDgBIAAAAAACgVQAFACACABQABAAABABQgZAEgiANQgeAJgaAOQgFgCgEgBQAJgFALgFQACgBABgBQAegMAcgIQAUgGAOgDIAAAA").cp();
	this.shape_51.setTransform(-6.2,-8.4);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.lf(["#BCEBFE","#279CE9"],[0,0.863],-0.1,-0.3,0.1,7.2).s().p("AiWAdQABAAAAgBQAGgKAAgIQAAgGgGgFQgIgKgPAAIAAAAQAIgGALgFQAJADALADQADABADAAQAFABAHABQAgACAggBQAJAAAIgBQAagBAXAAQAKAAAJgBQAhgBAhgCQAWgCAEgLQAFgNgPgKQgCgBgCgCQALADALADQAPANAKATQANATABAWQgYAAgRACQglACg9AEQgHABgBACIAAAAQAAABAEACQAUAHAYAFQALACAMACQAIABAHACQgOADgWAAQgNAAgJgCQgFgBgIgDQgIgCgGgBQgIgCgOAAQgFAAghACQgXAAgPgEQgJgCgHgFIgLgIQgHgDgLAAQgHAAgOABQgIABgFAAIAAAA").cp();
	this.shape_52.setTransform(-3,-3.6);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#99CCFF").s().p("AgEgKQAWgDAbAAQAmAAAIAGQAAACgBADQgEAIgTACQgeACgfABQgGgMgEgJIAAAAAgNgJQAFAJAGALQgDAAgEAAQgXABgXABQgIAAgIAAQgDAAgEAAQgBAAgBABIAAgBQgKgBAAgDQAAgDAbgGQAZgGAPgCQAFgBAFAAIAAAA").cp();
	this.shape_53.setTransform(-1,-6.8);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#CCE6FF").s().p("AABgXQADgBAFAAQALAAADAAQAEAABEAGQACAAACABQAJADAGADQgSgCgVgCQgcgDgFAAQgRgBgKAAQgBABAAAAQgHgDgGgCIAAAAAB8ACQgJgDgmAAQgaAAgYABQgGgKgEgEQABgBABAAQAAAAABAAQAKgBARACQAGAAAbACQAUACARACIABABQAGAFAAAEIAAAAAh7ATQAagOAegJQAigNAbgFQAGADAFACQgOAEgeAKQgMADgLAEQgYAJgVAKQgDAAgCgBQgGgCgFgBIAAAAAASAAQgFABgFABQgNACgZAGQgbAIAAADQAAACAKACIAAAAQgZAAgYgBIgBAAQASgJAXgIQALgEALgDQAdgJANgEQAEAEAGAJIAAAA").cp();
	this.shape_54.setTransform(-4.3,-8);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#333333").s().p("AgGgXQgBgBgBAAQgCgBgFgCQAFAAAEgBQADABADACQAAAAABAAQAGACAHADQAAAAABAAQAKgBARABQAFABAcACQAVADASACQgGgEgJgDQALACAKACQADABACAAQACABACACQAPAKgFALQgEAKgVACQghADghABQgKAAgJAAQgaABgXABQgJAAgIAAQghABgggCQgGAAgFgBQgDgBgDgBQgLgDgKgDQAEgCAEgCQAEABAFACQAFACAGABQACABADAAQAVgJAYgKQALgCAMgEQAegLAOgDQgFgDgGgCIAAAAAAbAAQAFAHAHAOQAegBAegCQAUgCAEgKQABgDAAgCQAAgFgGgFIgBAAQgRgDgUgCQgbgCgGAAQgRgBgKAAQgBAAAAAAQgBAAgBABQAEAEAGAMIAAAAAgvAYQABgBABAAQAEAAADAAQAIAAAIAAQAWgBAWgBQAEAAADAAQgGgNgFgIQgGgKgEgFQgNAEgdAKQgLACgLAEQgXAJgSAIIABAAQAYACAZAAIAAAA").cp();
	this.shape_55.setTransform(-4.3,-7.8);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AgBhnQgCAAgDgBQgSgDgUgCQgegDgZAAQgEAAgFAAQgFABgEAAQgQADgVAGQgcAIgeAOQgBABgBABQgLAFgJAFQgEACgEACQgLAGgIAFQgBABgCABQgUAOAAAIQAAASARALQAHAFAKAFQgCAIAAAIQAAAUAKANQAKAOAPAAQAAAAABAAQABAAACAAQALgBAggEQAKgBANgCQAbgDASgCQAAADAAADQAAATAKAOQAKANAOAAQABAAAAAAQACAAABAAQALgBAggDQALgCAKgBQA1gGAPgDQBJgMACgbQABgEgKgHQgLgJgQgDQgGgCgJgBQADgCADgBQAIgFAFgDQAQgBAZgDQAogGAAgHQAAgCgEgBQAMgEAKgEQAPgHAJgGQAEgCADgDQABgCACgBQAKgBAKgBQARgDAEgFQgHgCgXgFQgBAAAAAAQgBgBgBAAIACAAQAAgCAAgDQAAgHgHgCQAIgFAGgFQAGgHACgGQACgFgBgGQAAgCgBgCQgEgIgSgEQgDgBgDAAQgPABgNACQgQADgOAGQgRAHgJAJQgMALAAAMQAAAEgBAEQgMABgMABQgVgZg3gQQgKgDgMgDQgCAAgCgBQgLgCgIgCIAAAAAAYhpQAPADANAEQA1AQAXAXQACABAAABQAAgBAAgBQAAgBABgBQAAgOANgMQALgKASgIQAQgHATgDQAPgDAQgBQACAAACABQAFAAAGABQAXAFAGAMQABACABADQAAAGgCAGQgCAHgIAIQgDADgFADQAEAEAAAGQAAABAAAAQARAEAHADQAFABABACQACADgDACQgGAHgYAEQgHABgHABQgDADgFADQgJAHgRAHQgHADgHABQAAABAAABQAEAMg2AHQgWAEgQABQgBAAgBABQARAEANAKQANAJgCAHQgBAehSAOIgBAAQgQADg1AHQgLABgKABQghAEgLABQgDAAgCAAQgBAAgBAAQgYABgOgTIAAAAQgKgOgBgSQgLABgQACQgMACgKABQghAEgMAAQgCABgCAAIAAAAQgBAAgBAAQgYABgOgUQgLgOAAgVQAAgHABgHQgIgEgHgFQgSgMAAgUQgCgJAYgRQACAAABgBIAAgBQAMgHAQgJQAJgFALgFQACgBABAAQAfgPAegJQAdgIAVgCQAGgBAGAAQAaAAAgADQAYADATAEQALACALACIAAAAAjrAQIgBAAIAAgBQAAABABAAIAAAA").cp();
	this.shape_56.setTransform(5.9,0.5);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFCC00").s().p("AAkALQgJgBgJADIACgUQAHADAPAAIgGAPAgpARIAGgMIAEgHIAHgOQACABADACIgOAdQgDAAgDABIgCAA").cp();
	this.shape_57.setTransform(-12.2,3.6);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#CCCCCC").s().p("AAogHQAKABAGAGQAGAEgDAHQgCAHgJAEQgJAEgKgBQgKgBgFgFQgEgDAAgEQgBgDABgDQACgGAJgDQACgBABgBQAIgDAIABIAAAAAgXgNIgEgBIADgFIAAAAQABADAAADIAAAAAgjgYIgGAMIAAABIAAAAQgGABgDABIAAABIASAGQgBABgBAAQgHABgHAAQgHAAgCgFQgDgFADgFQADgFAHgDQAGgCAGABIAAAA").cp();
	this.shape_58.setTransform(-12.2,6.7);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#333333").s().p("AARgRQAJgCAKAAQACAAADABQARABAKAJQALAIgEALQgEALgPAHQgPAHgTgBQgSgCgIgJQgKgJADgLIAAgBQADgGAIgGQADgDAEgBQAFgDAFgBIAAAAAghgCIAJACQgCABgEACQgNAEgMgCQgMgCgFgFQgFgIAEgIQAFgIAMgFQAMgEAMACIgEAIQgGgBgGADQgHADgDAFQgDAFADAFQACAEAHABQAHAAAHgBQABgBABAAIAAAAAAngHQgIgBgIADQgBABgCAAQgJAEgCAGQgBADABADQAAADAEADQAFAGAKABQAKABAJgEQAJgFACgHQADgHgGgEQgGgFgKgBIAAAAAgMgMIgMgCQAAgCgBgDIAAAAIAFgKQAEACACAEQAEAFgCAGIAAAA").cp();
	this.shape_59.setTransform(-12.1,6.7);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#CC9900").s().p("ACXgBQgJgDgIgEIAHgKQANgBAMgBIgPATAhXAAQgPAAgIgCIACgKQALABANABIgDAKAifATIAAAAQgCABgEABIAOgeQgDgBgCgBIADgGQAGABAJABIgNAVIgFAJIgDAEAApgOQABAAACAAIgHANQgMgCgHgFIACgIQABAAAAAAQADACARAAIAAAA").cp();
	this.shape_60.setTransform(0.9,3.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#C12702").s().p("AgdAjQgWgHgVgTQgMgKgVgdQgBgBAAAAQABAAABgBQACAAACAAQACAAACAAQATgCAPAAQAPAIAOAGIgCAHIgJAjQADACACABQABAAAFAAQABAAABAAIAPgeIAHgOQAIAAAIAAQAHAEAJAEQAUAKAWAIIgIAMQACABAEAAQAFAAAHgBIAFgGQANAFAOAGQADAAgXADQgWACgfADQgqADgVAAIAAAA").cp();
	this.shape_61.setTransform(6.3,3.6);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.lf(["#996600","#FFCC00"],[0,1],-2.6,0.1,11,0.1).s().p("AgSgOQADADAEADQAGAGAHAEQADABADACQAFAEAGADQgPABgRABQgEgGAAgIQAAgDgBgHQAAgCAAgCIAAAA").cp();
	this.shape_62.setTransform(-1.9,-1.2);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.rf(["#FFCC99","#FF3300"],[0.008,1],-1.1,-1.1,0,-1.1,-1.1,2.8).s().p("AAgAPQAAAGgDAEQgDAEgCACQgFADgFACQgBAAAAAAQgtgSAAgWQAAgLAQgMQABgBACgBQABAAABgBQACgBAEgCQAFgCADAAQAQAAAIATQAGANAAAIQAAAGgBAEIAAAA").cp();
	this.shape_63.setTransform(-17.1,-2.6);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("Ag4ADQAGADAFAGIAAAAQgCACgEACQgCAAgCAAQAAAAgBAAQgKgFAKgIIAAAAAgGgKQACABADABQABABADACQgDABgCABQgSADgOAHQgFgFgFgCQADgBAEgBQAPgFAQgDIAAAAAALgMQAFgBAFAAQASgCARAAQAEABACACQgFAAgEAAQgSABgQADQgCgBgDgCQgBgBgCAAIAAAA").cp();
	this.shape_64.setTransform(-7,-8.5);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FF6600").s().p("ABMgGQgEAAgDAAQgCgGAAgEQAAgOALgPQAJgNASgMQARgMAVgIQAWgHAUAAQAGAAAFABQgVAAgXAIQgYAHgQAMQgTAOgIAKQgLANAAARQAAADACAGIAAAAABlAQQgFgEgDgEQgBgCgBgBQACgBACAAIABAAQAMALANAHQAJAFAHACQgMAAgEgDQgNgGgHgEIAAAAAi6AuQgFgFgEgGQAAgBAAgBQAAgDAGgBQABAAACAAQAAAAABABQAVAdANAMQAUAUAWAHQgRAAgDgCQgVgMgXgXQgDgDgEgDQgDgEgDgFIAAAAAiNAaQgGgEgGgDQgDgCgCgCQgJgGgHgFQgEgDgDgBQgBgCAAAAQgBgBAAgBQAAgCAGAAQACgBABAAQAOARAVALQASALAeAJQgRAAgDgBQAAAAgBAAQgOgGgPgIIAAAA").cp();
	this.shape_65.setTransform(14.3,-2.6);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FF3300").s().p("Aheg9QgFgHgGgEQgDgCgDgBQgDgCgEgBQAEAAAEAAQAKAAAHAAQAHADAEAJQABACABADQACAGAAAIQAAAEgBAEQgFABgFAAQACgKgGgLQgBgBAAgBIAAAAAEQhIIg7ABIgpA+QgFABgCAAQgYACgVAAQgCgGAAgDQAAgRALgNQAJgLASgNQAQgMAZgIQAXgIAUAAQAIABAFACQACAAAAAAQACABABAAQABABACABQAJAFACAMQAAABAAABIAAAAAC1AdQgHgCgJgFQgNgHgMgLIAAgBQAPgCAmgBQABABAEACQANAGAqALQgGACgRACQgSADgQABQgIABgHAAIAAAAAgvApQgegJgSgLQgUgLgPgRQACAAACAAQAlgDAZAAQAQAAAVABQAIAEAOAFQAHACAMAEQASAHAWAGQACAAADABQALAEAMADQALADANADQADAAgaACQgDAAgEABQgLAAgNABQgNABgNAAQgfACgVABQgKAAgIAAQgBAAgCAAIAAAAAjbBSQgJAGgDAJIAAABIgNgFIgKgEIgRgGIAAgBQACgBAGgBIABAAQABAAABgBQADgBADAAQADgBACAAIABAAIAEABIAMACIANACAjOgeQgCgJgGgGIAAgBQgFgGgGgDQgDgBgDAAQAFgDAGgCIAEAAQABAAABABQAFAEAFAFIABABQAFAFADAFQADAFABAHQgCAAAAAAQgGgBgHgBIAAAAAi4hHQAKgCALgCQAAAAABAAQACABAEACQABAAACABQACACACABQAHAEAFAGQAAABABAAQAFAFAEAMQACAEABADQgFAAgFABQgBgMgOgLQgDgCgDgDQgEgDgFgCQgDgCgEgBQgCgBgDgBQgDgBgDAAIgCAA").cp();
	this.shape_66.setTransform(9.8,-2.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFF00").s().p("AAlhDQAAAAABAAIgBABIAAgBACNAHQgMgDgLgEQAKAAAJgDQAKgDAJAAQACAAAHABQAIABACAAQAJAAAMgGQAEAEAFAEQgDAAgCABQgMABgPACQgOACgSADIAAAAABoAcQAHAEAJADIgQAVIgFAFQgHABgFAAQgEAAgCgBIAIgMIAPgVAiLAYQgJAAgIgBQgHgBgGgBQgJgBgGgBQgHgCgFgCQAAAAAAAAQAGgBAEgEQADgBADgFQACgDABgFQADAAAIAAQAHAAADACQAEACAFADQAGAEAIAAQAIgBAEAAQAFAAABACQADACAJACQAHABAFABQAAAAAAABQADAFAFAGQgFAAgFAAQgLAAgLgBQgNAAgLgBIAAAAAAGAjIgNAhQgBAAgBAAQgFAAgBgBQgCAAgDgCIAJglQAIAFAJACIAAAAAjMA7IACABQgBAAgBAAIAAgB").cp();
	this.shape_67.setTransform(4,-0.6);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.lf(["#CC9900","#FFFF00"],[0,1],-2.9,4.7,-2.9,1.1).s().p("Ah3gNQAHgCAKgBQAJgBAJgBQAFgBAFAAQAcgEAQgCQAJgBAGgBIABAAQAOADACACQAHAEAcAQQAYALAFABQAXACAeAAQADAAADAAQAVgBAYgBQACAAAFgBIApg8IA7gBQABAOgPAOQgDADgCACQgcAUgIAFIACAAQADAIgRAGQgDABgEACQgEgDgBgBQgmACgPACQgDABgCAAQABACABACQgMAGgJAAQgCAAgIgBQgHgBgCAAQgJAAgKADQgJADgKACQgDgBgCgBQgWgFgSgHQgMgEgHgDQgOgGgIgEQgVgBgQAAQgZAAglADQgCAAgCAAQgBAAgBAAQgGABAAACQgBAAABABQABABABACQAAABAAACQABAHAAAFQAAAIAEAHQgCAAgCAAQgCAAgCAAQgBAAgBAAQgCAAgCAAQgGACABADQgFAAgHgCQgJgBgCgCQgCgCgFAAQgEAAgIAAQgHAAgGgDQgGgEgEgDQgDgCgHAAQgHAAgEAAQABgEAAgGQAAgKgGgNQgIgRgQAAQgEAAgGACQgEACgCABIAAAAQALgHAPgGQAGgDAGgCQgDADgBAAQAAABAAAEQAAAGAiAEQADABAEAAQAHABAGAAQAAAAACABQALABAIAAQACAAAkgFQAFgBAFAAIAAAA").cp();
	this.shape_68.setTransform(9.3,-4.5);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("AhNhdQgIAAgJAAQgEAAgEAAQgXAAgWADQAAAAgBAAQgKACgLACIAAAAQgUAEgPAGQgGACgFADQgBAAgBABQgFACgEADQAAAAgBABIAAAAIgBAAQgGACgGADQgPAGgLAHIABAAQgBABgBAAQgCABgBABQgRAMAAALQAAAWAvARQAFACAIACIgDAGIgHAOQgMgCgMAEQgMAFgFAIQgEAIAFAIQAFAHAMACQAMACANgEQAEgCACgBIANAEQgDALAKAJQAKAJASACQATABAPgHQAPgHAEgLQAEgLgLgKQgKgJgRgBQgDgBgCAAIAGgRIADgKQALAAALAAQAFAAAFAAQADAFADAEQAEADADAEQAXAWAVAMQADACARAAQAWgBApgDQAfgCAWgCQAXgDgCgBQgPgFgNgFIARgVIAPgTQADAAAEAAQAZgCgDgBQgMgDgMgDQASgCAPgDQAPgCALgDQADAAACgBQAHAFANAGQAEACAMAAQAGAAAIAAQARgBASgDQAQgDAHgCQgqgJgNgGQAEgBACgBQASgGgEgIIgCAAQAJgFAbgWQADgCACgDQAQgOgBgOQAAgBgBgBQgBgMgKgFQgBgBgCgBQgBAAgBgBQgBAAgBAAQgGgCgHgBQgFAAgGAAQgUAAgWAHQgVAHgRAMQgSAMgJAOQgLAPAAANQAAAFACAGQgeAAgXgCQgEgBgYgNQgcgQgHgEQgEgCgNgDQAAAAgBAAIAAgBQAAAAgBgBQgQgUgUgGQgJgCgOgBQgEAAgIAAIAAAAAgkhfQAWAGARAWQAOADAEACQAIAFAbAPQAUALADABQAQACAUABQAAgDAAgCQAAgPALgPQALgPASgNQATgNAWgHQAZgJAYAAQAXAAANAHQACABACABQAMAGACAPQAAABAAAAQACAQgRAQQgDADgDACQgVASgKAHQACAJgOAGQAOAFAZAGQAEAAACACQABACgBADQgCACgEABQgHACgSADQgTADgRABQgfACgJgFIgBAAQgJgEgGgEQgKACgOACQgBABgBAAQAHADgGAEQAAACgGABQgCABgFAAQgFABgOABIgZAfQAJAEAKAEIABAAQAIADgEAEQAAACgFACQgCABgFAAQgFABgNACQgWACgfACQhWAHgIgHQgWgMgXgXQgEgEgDgDQgCgDgDgCQAAAAgCAAQgFgBgGAAIgFAQQASADALAKQAMALgEAOQgFAOgSAIQgUAJgYgCQgXgCgNgMQgKgJAAgKQgRAGgRgDQgSgDgIgKQgGgKAGgKQAGgKAPgGQALgEALAAIAFgKQgDAAgCgBQAAAAgBgBQg0gTAAgZQAAgNATgOQACgBABgBQABAAAAAAQAAgBABAAQAMgHAQgHQAFgDAGgCQABAAAAAAQAEgDAGgDQAAAAABgBQAGgDAHgCQABgBAAAAQAAAAABAAQAPgGAVgEIAAAAQALgCAKgCQABAAAAAAQABAAAAAAQAXgDAYAAQAEgBAFAAQAKAAAHABQAJAAAEAAQARABALADIAAAAAA8AgIgOAVQgXgJgTgKQgHgFgHgEQATgBAggBQAOgBAMAAIgHAKAAqAdQgPABgMABQAMAGANAGIAKgOQgEAAgEAAIAAAAAjUAZQAGABAHABQAIABAJAAIgCAKIgCAVQgFABgFADQgEABgDADIgOgDQACgGgEgFQgCgEgEgCIANgWAjJAhQgCAAgBAAIgIANQACACACACIAAAAQADAEAAAEQABAAAAAAQADgBAEgCIACgVQgDgBgDAAIAAAA").cp();
	this.shape_69.setTransform(8.3,-1);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#7083CB").s().p("ABPAAQgQABgbAEQABgEAAgCQAAgIgDgGQAOAAANACQAFABAHADQAHAFAAACQAAACgBAAIAAAAAAZAGQgJABgJABQgIABgHACQgBgDgCgEQgEgKgFgFQARgDACAAQAMgBAJAAQAAABABABQAHALgDAIIAAAAAghgJQAOAJABAMQgkAFgCAAQgIAAgLgBQgBgHgDgGQACgBAFgCQAOgFARgEQAEAAAEAAIAAAA").cp();
	this.shape_70.setTransform(-1.7,-7.1);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#99CCFF").s().p("AA1gGQgBgCgBgDQgEgJgGgDQAIAAAEABQAOAAAJADQAUAGAQASQABAAAAABIAAAAIAAABQgFABgKABQABgCAAgBQAAgDgHgDQgHgCgFgBQgNgDgOAAIAAAAAhPAIQAGAGACAKQgEgBgDAAQgigEAAgGQAAgEAAgBQABgBADgCIABAAIAAgBQAAAAABgBQAEgDAFAAQABAAAAgBQAEABACAAQgLAGALAGQAAAAABAAQACAAACgBQADgCADgBIAAAAAhEACQAOgFARgEQAFgCADAAQAFACAFADQACACADACQgEAAgEAAQgRACgOAHQgEACgDACQgDgFgFgFIAAgBAgxgQIACAAQADAAADABQgQAEgPAFQgDABgDABQgCgBgBgBIgEAAQAPgGAVgDIAAgBAAWgUQgRAAgQACQgGABgEAAQgDgCgDAAQAVgDAWgBQADACADABIAAAAAAngGQgIABgOAAQgDABgPACQAAAAAAAAQgFgGgIgFQAPgCASgBQAEAAAFgBQAHAFAEAGIAAAA").cp();
	this.shape_71.setTransform(-3.6,-8);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.lf(["#06A5E8","#00121A"],[0,0.859],5,-10.8,4.8,-1).s().p("AAAAAQAAAAAAAAQAAAAAAAAIAAAA").cp();
	this.shape_72.setTransform(-17.4,4.3);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#996600").s().p("AgMgFIAMgCIAAAAIADADIAIAEIAFACQgGADgFADQgDgCgDgDQgKgFgEgCIADgB").cp();
	this.shape_73.setTransform(-5,7.2);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.lf(["#06A5E8","#00121A"],[0,0.859],0.2,-3.3,0.3,3.5).s().p("Ag4APIAAAAQAEgDAEgCQAPgKAJgKIADAAQACACAAACQAAADACACQACABACAAQAIAAAFgBQAIgBAHgCQAFAAAEgBQARgEAOgGIACAAQgBADgBADQgBAFgCAEQgCAEgJAEQgdAEgbADQgOABgOAAQgHAAgGgBIAAAA").cp();
	this.shape_74.setTransform(-11.6,2.7);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.lf(["#FFFFFF","#66CCFF"],[0,1],-2.7,0,3.1,0.6).s().p("AgeAFQABgBACgDQACgBADgEQASADARAAQACAAADAAQAGACAHAEQgDAAgEAAQgBAAgBAAQgGAAgGAAQgFAAgEAAQgBAAgCAAQgOAAgOAAIAAAA").cp();
	this.shape_75.setTransform(-2.8,2.5);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#CCCCCC").s().p("AgjgNIABgJQAEgBADAAQAEgBADABIgMAKIgDAAAgpgMIAMAHQgDABgEAAQgJABgFgCQgEgCACgFQACgEAHgDIABAGIAAABIABAAIAAAAAgSgQIAGgEQAAABAAADQgBABgBACIgEgCIAAgBAAegCQABAAABAAQAMgBAGADQAEAAgBAGQgCAGgKAGQgIAFgOABQgMABgGgDQgFgDADgGQAAgBABgBQABgFAJgEQAJgCALgCIAAAA").cp();
	this.shape_76.setTransform(-3,8.1);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#666699").s().p("AAXAGIAPgMQAMACAKAAQABABABAAIgTAJQgIgBgLABQgBAAAAAAIAAAAAg3AKIAAgBIgCgGIgCgHIgCgHQAIgBAGAAIAAAEIAAAIIgBAJIgGABIgBAAAAGgNIgGAYQgFACgFACIABgOIAAAAIAAgDIABgIQAAgCAAgCQAEAAAEABQAEAAACAAIAAAAAgaACIgFAEIgBAAIgNADIAMgJIAMgKIAAAAQAGACAEABIgBAAIgOAJ").cp();
	this.shape_77.setTransform(-1.6,5.7);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#3E3F5B").s().p("AgtACQgHAAgHABIgBgDQAHAAAFgCQAAAAABgBQABAAABgBIAAAGAALgJIgDAKQgDAAgDAAQgEgBgEAAQAAACgBACIgCADQgFgBgGgCIANgIIAAgEQAEAAADAAQAFAAAGgBIAAAAAA9AKQgJAAgNgCIAGgFQAIAEAIADIAAAA").cp();
	this.shape_78.setTransform(-1.8,4.1);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.lf(["#FFFFFF","#66CCFF"],[0,1],-2.2,-0.2,2.3,0.2).s().p("AgYAAQAbAAAWgEQgEADgFABQgCABgBAAIgBAAIAAABQgLACgPABQgFgDgFgCIAAAA").cp();
	this.shape_79.setTransform(16.5,1.7);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#6699CC").s().p("AAHgDQgEADgEACQgBAAgBABQgBAAgBAAQAAABAAgBQAAAAgBAAIAAAAIABAAQABgBACgBQADgBAEgDIAAAAIABAAQAAAAAAAAIABAA").cp();
	this.shape_80.setTransform(18.5,1.6);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.lf(["#FFFFFF","#66CCFF"],[0,1],-2.8,-0.2,2.8,0.4).s().p("AgVAFQAmgFATgMQgMAMgoAKQgGACgKABQgCAAAAAAQAAAAACgBQAGgDAEgDQAAAAABgBIAAAA").cp();
	this.shape_81.setTransform(21.7,0.6);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.lf(["#FF0000","#330000"],[0.039,1],0.1,-1.8,0,1.9).s().p("AAbAAQgTALgmAHQATgPAAgRQADgBACAAQATgBARgBQABAEAAAEQAAAFgEAEIAAAA").cp();
	this.shape_82.setTransform(22.5,-0.7);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFCC00").s().p("ACFgzQgFgCgGgBQgEgCgIgBIASggIAiAAQABADAAAEQAAALgMAJQgDACgIAFQgEACgDACIAAAAAiFBXQgCABgBACIgIgFIAAAAIgGgEIgMgHIAGgBQAFACAKAHQAEADAEACIAAAA").cp();
	this.shape_83.setTransform(9,-0.6);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#93CCE3").s().p("ABNgEQgMgCgLgDQgEgBgEgBQgBgBAAAAQAAgBAEgBQACgBADgBIAAABIAAAAQAAADAdAFQgDACgDABIAAAAAAagsQgCgLAggUQANgHARgEQAQgEAOAAQADAAADAAIAAAAQgkADgYAOQgVAMgHARQgEAAgEAAIAAAAABoAAQgGAAgTgEQADgBACgBQAAAAABAAQABAAABAAQAEABAIABQAGACAEAAIAAAAQACAAAAABQAAAAAAABQgCAAgDAAQAAAAAAAAQAAgBgBAAQAAAAAAABQgBAAAAAAIAAAAAgUBUQAEABADABQABAAAAABQABAAAAAAQAdAABTgCQABABABABQgsADhIABQgFAAgOgFQAGgBAFgBQAAAAABAAIAAAAAgXBTQgFABgGABQgJgDgOgGQgBgBgCgBQgBAAgBgBQgIgDgIgEQgHgEgGgDIAAgBQACgCAKgCQAKAGAMAHQAGADAFADQAOAGAJAEIAAAAAhsAnQAKAFARAJQgJACgDADQgFgDgEgDQgIgEgGgEQgCgCgDgBQAGgBAGgBIABAA").cp();
	this.shape_84.setTransform(10.6,-2.1);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.lf(["#FF0000","#000000"],[0,1],2.4,-1.3,8.4,4.8).s().p("AgPgKQAIABAEABQAFABAFACQATAFAIAMQgHgCgHgBQgNAAgNABIABgBIgBAAIAAgBQgCgDgDgEQgDgCgGgEQgGgDgHgDQAJAAAHABQAAAAAAAAIABAAQAAAAABAAIAAAA").cp();
	this.shape_85.setTransform(21.6,-5.2);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#006666").s().p("AByhQIAAAAQABAAAAAAIAAAAQAAABAAAAQAAAAgBAAIghAAIgTAgIAAABQgBAAAAAAIgBAAQAAgBAAAAIATghIAAAAQAAAAABAAIAiAAAB7gUQAAAAABAAQABAAAAAAIAAABQAAAAgBAAQgGAAgKABQgQABgJABQgPABgGABQgFABgDABQgBAAAAABQgCAAgDACQAAAAAAAAQgBAAAAAAIgBAAIAAgBQADgBADgBIAAAAQAEgCAGgBQAFgBAPgBQAJgBARgBQAIgBAHAAIAAAAAgzBPQgBAAAAAAQgFABgGABQAAAAgBAAQAAAAgBAAIAAAAIAAgBIAAAAQAGgBAFgBQABAAAAAAQAkgGAkAAQAVAAAUAAQABAAAAAAIABAAIAAAAQAAAAAAAAIgBAAQgVABgVgBQgjAAgjAHIAAAAAAWAtQgBABAAAAQgDgBgFAAQgRAAgKgBQgjAAgbACQgWABgMACQgKACgCACIAAABIgBAAQAAAAgBAAQAAAAAAgBIAAAAQADgDAJgCIABAAQAMgCAXgBQAbgCAjAAQAKABARAAQAEAAADAAQABAAAAAAQABAAAAABIAAAAIAAAA").cp();
	this.shape_86.setTransform(13.7,-1.6);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#3399CC").s().p("ABBgRIAAAAQAAAAABAAQAAAAABAAIAAAAQAPgBANAAQAHABAGADQAFAAAFACQgGAAgJABQgQABgJABQgQABgFABQgGABgDACIgBAAQgdgGAAgDIABAAIgBgBIABAAQAHAAAngDIAAAAAAAgqQAGgQAUgNQAYgOAkgCIAAgBQACAAABABIABAAQAQACADAMIgiAAQAAAAAAABIgBAAIgSAhQgHgBgJAAQgBgBAAAAQgBAAAAAAIgBAAQgBAAAAABQAAgBgCAAQgNAAgPgBQgEAAgCAAIAAAAAh0A4QgSgJgKgFQAegDAugBQABABABAAIAAAAQAAAAABgBQACAAADAAQAfAAAYABQACABADABQADADAEADQAFACAEADQgDAAgEgBQgSAAgKAAQgjAAgbABQgXACgMACIAAAAAAxgEQAEgBAFgBQAFgBAPgCQAJAAARgBQAJgBAHAAQAAAAABAAQAPAEAJAEQgNACgSABQgRAAgVAAQAAAAAAAAQAAAAgCAAIgBAAQgEAAgGgBQgHgCgFgBQgBAAgBAAIAAAAAARA1QAXAOAQAMQgUABgVAAQglgBgjAHQgBAAgBAAQgJgEgNgHQgGgDgFgDQgNgHgKgFQAMgCAWgCQAbgBAjAAQAKAAASABQAFAAACAAQABAAAAAAIAAAAAg4BWQAjgGAkAAQAVABAUgBIABAAQAEAEAEAEQhQABgfAAQgBAAAAAAQgBAAgBAAQgDgBgEgCIAAAA").cp();
	this.shape_87.setTransform(14.2,-2.4);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.lf(["#FF0000","#330000"],[0.039,1],-0.9,-2.2,0.8,7.3).s().p("Ag4ATQgEgMgIgJQAigBAUgLQADgCgEgBQgEgBgDgBQAKAAAKABQACAAADAAQAEAAAEAAQAPAAANABQACAAAAAAIABAAQAIAEAFADQAGAEADAEQADACACADIABAAIAAABQgnADgHABIgBAAQgDABgBAAQgFABAAABQAAABABABQAFABAEABQguAFgXgBQgGAAgFAAIAAAA").cp();
	this.shape_88.setTransform(13.7,-4.7);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.lf(["#FF0000","#330000"],[0.039,1],0.2,-2.4,0,2.5).s().p("AAuATQgWADgaACQgCgBgCgBQgZgBgfAAQgCAAgCAAQAGgJAAgNQAAgJgCgJQAEAAAHAAQAWABAugFQALACAMACIAAABIABAAQAAAAABAAQAAAAAAAAQATADAGABQABARgVAPIAAABIgBAA").cp();
	this.shape_89.setTransform(14.3,-0.7);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#660000").s().p("AhMgfIAAgBIAAAAQABAAAAAAIABAAQADAEAEAFQAIAKAEAMQADAIAAAJQAAAPgHAJQAAAAgBAAIAAAAQgBAAAAAAQAHgKAAgOQAAgJgDgHIAAgBQgEgMgJgKQgDgFgDgDIAAAAABJgPIAAAAQAAAAgBAAQAAAAgBAAIAAAAIAAgCIgBAAQgCgDgDgDQgCgFgHgEQgFgDgIgDIAAAAQAAgBAAAAIABAAQABAAAAAAQAAAAABABQAHACAFAEQAHAEADAEQACAEADADIAAAAIAAAAIAAACABNACQAAAUgTAPQgBAAgBAAIAAAAQgBAAAAAAIAAAAIAAAAQAUgPAAgUQAAAAAAAAQAAgBABAAQABAAAAABQAAAAAAAAIAAAA").cp();
	this.shape_90.setTransform(13.6,-2.5);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#407DD9").s().p("AAWgIQAEAGACAGQAAAAAAABQgLABgKABIAAAAQAAgBgBABIgBAAIAAAAQgFABgGAAQAAgIgDgIQAGAAAHAAQAJAAAJAAIAAAAAAuACQgGABgHABQAAgFgCgGQACABAEAAQALADAAADQAAAAAAAAQgCABgBABIABAAAgPAJQgHAAgGAAQgIAAgHAAQgCgHgDgDQAEgCADgCQAHgCAPgBQAEAIAAAJIAAAA").cp();
	this.shape_91.setTransform(5.2,-6.5);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.lf(["#FF0000","#330000"],[0.039,1],0.2,-2.5,0,2.6).s().p("AA7ARQgvAAgcADIAAAAQgGABgGABQACABADACQgDAAgCAAQgTAAgSgDQACgEACgFQAHgPAAgJQAAgFgBgFQAMAEAVAAQAIAAAUgDQAMgBARgCQAIgBANAAQACAAAFAAIAAABQADAJAAAJQAAAMgHAKIAAAA").cp();
	this.shape_92.setTransform(1.4,-0.2);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#262626").s().p("AgaAOQgEAAgFAAQgCgIgEgEQgKAEgGAFQgFAAgEgCQAHgFAKgEQABAAACgBQgBgBgBAAQAAgCAEgBQABAAADAAQABAAABABQALgDARgDQAAAAABAAQgBgBgBAAQAAgBABAAQADgCAEAAQACAAABABQAAAAAAAAQAAABAAAAQABABABABIAAAAQAOAAAQABQABABABAAQgBgBgBgBQACgBAEAAQABAAABAAQACACABACQACAAABAAQAJABAGACQADABADADQgGgDgPgBIAAAAIAAAAQABABABACQADADAAAHQgDABgDAAQgCgIgEgEQgBgCgCgCQgQgBgOAAQgBAAgBAAQABACACADQADAFAAALQgFAAgFAAQABgKgDgGQgBgCgDgDQgPACgNAFIABAAQABABACACQACAFACAGIAAAA").cp();
	this.shape_93.setTransform(3.5,-7.1);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#990000").s().p("AATAAQAJAAALgBQAAgBAAAAQADAAADAAQAGgBAGgBQAJgCAFgBIAAgBQAAAAABAAQADABAEABQAEABgCABQgVAKgiABQgEgEgDgDIAAAAAARAAQADADADAEQgYADgbgCQgggCgVgKQAEABAFABQAEABAFABQAKAAAMAAQAFABAEAAQAIAAAIAAQAFAAAHAAQAEgBAEAAQAGAAAHAAIAAAA").cp();
	this.shape_94.setTransform(4.1,-5.7);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FFFFFF").s().p("AAygDQgJAAgKgBQgFAAgFAAQgBAAgBAAIAAAAQgBAAAAgBQgCgCgDgCQAAAAAAAAIAAAAQAFAAADAAQAOABANADIAAABQABAAABABIAAAAAgZAAQgEAAgEgBIAAAAIAAgBQABgBABAAQAKgGAPAAQABAAABAAQAEACAFADQgNAAgMADQgCABgDAAIAAAAAggADIgLAHIgGAAIAJgJIABAAQAEABADABIAAAA").cp();
	this.shape_95.setTransform(1.6,-7.9);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.lf(["#FF0000","#330000"],[0.039,1],0.5,-2.3,0,7.7).s().p("AgvAQQgCgOgJgKQgGgHgGgEIAAAAQACAAAVgBIABAAIAAAAQAVANAeACQAcACAagDQAIAIAEAMQgEAAgDAAQgNAAgHABQgSACgMABQgUADgIAAQgVAAgMgFIAAAA").cp();
	this.shape_96.setTransform(0.6,-4.2);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#99CCFF").s().p("AgEgOQgDgBgBgCQAQABARADQACACACABQgNgCgOgBQgCgBgEAAIAAAAAAggGQABAAABABQgBAAgBAAQgQgBgOAAIAAAAQgBgBgBgBQAAgBAAAAIAAAAQABAAABAAQAFAAAFAAQAKACAJAAQABAAAAABIAAAAAAkgKQANAEAMAFQgGgBgJgCQgBAAgCAAQgBgBgCgCQgCgCgCgBIAAAAAAHAAQgCgBgBgDQABAAABAAQAOAAAQACQACACABAAQgIAAgKAAQgIAAgGAAIAAAAABNAIQgFACgJABIgBAAQABgBACgBQABgBAAgBQAAgDgMgCQgDgBgDgBQgBAAgBAAIAAgBIAAAAQAPABAGACQADAAADADQACAAABACQAAAAABABIAAAAAgLgHQABAAABABQgBAAAAAAQgRACgLAEQgBgBgBAAQgCgCgCgBIAAAAIAAAAQADgBACgBQAMgDAPAAQAAAAABABIAAABAg0gGQgDAAgCAAQgBAAgBAAQAHgFAFgDQAIgBAIgBQADABADABQgPABgKAGQgBAAgBABIAAAAAgCAAQgPAAgGACQgEACgDADQgCgCgBgDIgBAAQANgDAPgDQADADABABIAAAAAgwAAQABAAABABQgCABgBAAQgKAFgHAGQgFgBgEgBIAAgBIgBAAQADgFAIgGQADAAABAAQABAAABAAIgJAGIAGABIALgGIABAAQABAAABAAIAAAAAgjASQgMgBgKgCQAGgFAKgFQAEAFACAIIAAAA").cp();
	this.shape_97.setTransform(3.5,-7.5);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#555555").s().p("AAqgBQgCgBgCgCQAGABAGACQABABACAAQgBAAgBAAQgDAAgCAAIgBAAQAAAAAAAAQgBAAgBAAIgBgBAADgIQACACACABQAAAAABAAQACACADACQgDAAgCAAQgEAAgCABQgBAAAAAAIgBAAQAAAAAAAAQgEgCgGgCQgBgBAAAAQgEgBgDgBQABAAABAAQALgBAIAAIAAAAAgtABQAAAAABAAQACAAADAAIAAAAQAEABAEABIAAAAQACABACABQgDAAgBAAQgEACAAABQgBAAgBgBIgBAAQgCgBgFgBIAAAAQgCAAgBAAQgBAAgDABQADgDAEgCIAAAA").cp();
	this.shape_98.setTransform(2.2,-8.4);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#333333").s().p("AA4ASQALgDAMgCQABAAABAAQAKgBAJABQAIABAGADQAHAEgCAKQgEAMgRAJQgQAJgZACQgVACgMgFQgFgDgCgEQgCgEADgGQACgFAGgFQABgBACgBQAEgDAGgDQABAAABgBQABAAABgBQAAAAABAAQAGgDAGgCIAAAAAAAALQgHADgCAEQgCAEAEADQAFACAHgBQAEAAADgBIAGADIAAABQAAAAgBAAQgHACgJABQgNABgIgEQgJgEAEgIQAEgHANgHQADgBACgBIADAKAh3g/IAUAAQABAAAAABQACABAAACQAAACgCACQgBABgCAAIgSAAQABgCAAgDQAAgCgBgCIAAAAAAtAJQgCAGgJAGIgHgEQABgCABgCQAAgCAAgBIAOgKQABAAABABQAAABABACIgBAEIAAABAAhgCIgMAIQgDAAgEAAQgDAAgEABIAAgIQABAAAAAAQAFgBAGAAQAIgBAGABIAAAAABJAcQgLABgJAFQgJAEgDAEQgBABAAABQgDAGAHADQAGAEAMgCQAOgBAIgFQAKgFACgHQABgFgEgCQgGgDgMABQgBAAgBAAIAAAA").cp();
	this.shape_99.setTransform(-7.3,4.9);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.lf(["#FFFFFF","#006699"],[0,0.859],-0.7,-1.1,-0.9,8.6).s().p("AAMgKQAMABAUADQABAAAAABIABAAQAFAFAGAMQgCgCgEgDQgEgDgDgCQgFgCgRAAQgEAAgMABQgKABgFgBQgKAAgMAJIAAAAQgBgBAAAAQgLgKgNgGQAGgDAMAAQAFgBASAAQAXAAAEABIAAAA").cp();
	this.shape_100.setTransform(-11.5,-5.4);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.lf(["#06A5E8","#00121A"],[0,0.859],5.3,3.5,-5.2,-3.3).s().p("AgjgUQAGgKACgEQALgOAQAAQAOAAALAPQAJAMABARQAAADABABQgBADAAACQgBARgJANQgLAOgOAAQgQAAgLgOQgCgEgDgJQAFAAACAAQABAAABAAQABAEADADQAHANAMAAQAJAAAIgMQAHgLABgPQAAgCAAgCQAAgBAAgCQgBgPgHgKQgIgNgJAAQgMAAgHANQgDADgBADQgBAAgBAAQgCAAgIACIAAAA").cp();
	this.shape_101.setTransform(-18.4,-1);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.lf(["#BCEBFE","#006699"],[0,0.859],0.9,-5.3,0.7,4.3).s().p("AhZAVQAEABADABQADAJACAEQALAOAPAAQAQAAALgOQAJgNACgRQAAgCAAgDQAAgBAAgDQgCgRgJgMQgLgPgQAAQgPAAgLAOQgCAEgGAKQgBAAgCAAQgBABAAAAIgCAAQADgLAIgIQAIgKALgEQAFgBAFgBQANgDAOgBQAPgBAVAAQAZAAARAEQAJABAEADIABAAQAGAEAGAHQAJAMACAOQABAFAAAGQAAAHgHARQgCAFgCAEQgDAGgCABQgCADgBABQgDADgBABQgCABAAABQgBAAgBAAQgEACgIACQgCAAgCABQgEABgFAAQgJACgMABQgEAAgEABQgIAAgGABQgKAAgKAAQgMAAgQgBQgRgCgMgPQgIgJgDgLIACAAAAeg1QgEAAgZAAQgQAAgFAAQgMAAgGADQANAHALALQAAAAABABIAAAAQAMgJAIAAQAFABAMgBQAMgBAEAAQARAAAFADQADABAEADQAEADACACQgGgOgFgFIgBAAQAAAAgBAAQgUgEgMgBIAAAAAgmA2QgBAAAAAAQAAAAABAAQAGABAGAAQAOAAAMgBQAdgDAdgEQAJgEADgGQABgEACgFQABgDAAgDIgBAAQgOAGgRAEQgEABgFAAQgIACgHABQgIACgHgBQgDAAAAgBQgCgCAAgDQAAgCgBgCIgEAAQgJAMgOAKQgEACgEADIAAAA").cp();
	this.shape_102.setTransform(-13.3,-1.1);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.rf(["#FFFFDD","#FFCC00","#BA9501"],[0,0.471,1],-1.5,-0.3,0,-1.5,-0.3,1.9).s().p("AAVAWQgDgBgDAAQgCgBAAAAQgMgCgKgDQgkgJAAgEQAAgDAkgKQAKgEAMgEQABAAABAAQAAAAABgBQACAAAAAAQAIgCACAAQABAAABAAQADABADABQACACADADQAEAFABAHQAAACAAABQAAADAAACQgBAGgEAFQgFAGgGABQgBAAgBAAQgCAAgFgBIAAAA").cp();
	this.shape_103.setTransform(-23.9,-1);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#000000").s().p("AgfhMQgIAHgCAGQgVABgDAAIAAABIAAgBQgFgCgIgCQgRgEgZAAQgYAAgPACQgNABgOACQgEABgFABQgLAEgJAKQgHAJgDAKIABAAQAAABgBAAQgMADgMAEQgkAKAAAFQAAAEAkAHQAMADALACQABAAABABIgBAAQADALAHAJQANAPAQABQAQACAMAAQAKAAALgBQAHAAAIgBQAEAAAEgBQAMgBAKgBQAEgBAFgBQACAAACgBIABAEIABAHQgCABgDABQgNAGgEAIQgEAHAJAEQAIAFAPgCQAJgBAHgCQABAAAAAAIAIAFQgGAFgCAFQgDAFACAFQACADAFADQAMAGAVgCQAXgCAQgJQARgKAEgMQACgKgHgDQgGgEgIAAIASgLQACABABABQAOAGAJADIAAAAIAAABIAAAAQABAAAAAAQABAAAAAAQAOAFAFAAQBKgBAsgDQgBgBgBgBQgEgEgEgDQAAAAAAgBIAAAAIgBAAQAAAAgBAAQgPgNgXgOIAAAAIAAAAQAAgBgBAAQAAAAgBAAQgEgCgFgDQARgBAMgCQAAAAABAAQAAABAAgBQABAAABAAQABAAABAAQAKgCAGgBQAqgLAMgLQAEgFAAgGQAAgEgBgEQASgBAOgBQgKgEgPgEIAAgBQAAAAgBAAQgBAAAAAAQgFgCgFgBQgIgMgTgHQADgCAEgCQAIgEADgDQALgIAAgLQAAgEgBgDQABAAAAgBQAAAAAAAAIAAAAQAAgBgBAAIAAAAQgEgMgQgDIAAAAQgCAAgBAAQgDAAgDAAQgOAAgQAEQgRAEgNAHQggAUACALQgJAAgLAAQAAAAgBAAIAAABQAAgBAAAAQgCgCgCgBQgDgCgCgBQgDgCgEgCQgLgGgNgDQgGgCgGgBQgQgDgTgBQgKAAgKABQgBAAgCAAQgGABgIABQgFADgGAFQgEACgDADIAAAAABShYIAHAHQAGABAGABQALACAGAFQABAAABABQABgBAAAAQACgFAEgFQAIgHAJgGQANgKAUgGQAVgHAYgBQABAAAAABQACAAACAAQAUABAJAIQAGAFACAFQABAFAAAFQAAANgOALQgFADgFAEQANAGAGAJQASAFARAGQADABABADQABADgDABQgDADgGAAIgTACQAAADgBACQgCANgTAIQgQAIgUAEQgGACgGABQgNADgOABQAHAEAHAFQATANAPAOQACABgBADQAAABgDACQgDABgEABQgQABgPABIgBAAQgnACgoAAQgIAAgHgBQgOgCgLgEIAAAAQgDgCgEgCQADADABAEQADAQgSANQgKAIgOAFQgVAHgagBQgBAAAAAAQgWgBgLgJQgDgCgBgDQgDgJAGgIQgLABgLgBIAAAAQgKgBgHgEQgOgHAGgKQAFgJAMgGQgFABgGAAQgdADgeAAQgBAAAAAAQgHAAgHgBQgYAAgNgLQgQgNgFgPQgVgFgUgGQgIgCgGgCQgMgGAMgHQAIgFAMgEQARgFASgFQACgEABgEQAHgNARgKQAEgDAFgBIAAAAQAJgCAJgCQAWgEAYAAQAYgBAXADIABAAQAQABAMAFIAKAAQABgCABgCQAKgLARgKQADgCAEAAIAQgCQABAAABAAQAJgBAKAAQAdAAAaAHQADABACACIAAAAAjQAMQAGgBAEgGQAEgFABgEIASAAQACAAABgCQACgBAAgCQAAgCgCgCQAAgBgBAAIgUAAQgBgHgEgFQgCgCgCgCQgDgCgDAAQABgEADgDQAHgMAMAAQALAAAIAMQAHALABAOQAAADAAACQAAADAAACQgBAMgHALQgIANgLgBQgMAAgHgMQgDgEgBgDIAAAAAAFA/QgKABgLAEIAHgaIADgMQABAAACAAQADAAACAAQAEADAFADIAAAAQAAABAAAAQABAAAAAAIABAAQAGADAHAEIgGAFIgPAOAhAAjQACgCACgCQAOAAAPAAQADAAACAAIAAAEIgNAKIAAAAQgGgBgIABQgGABgFABQAAAAgBAAIABgEIAAgIAgcAwIACgDIAAAIQgBgBAAgCQgBgBgBgBIABAAAgmBHQAJgGACgHIgBAOQgBABAAAAQgBAAgBABQgBAAgBAAIgFgDAhJBDIABAAIAAAAIgBAAAgxA/IAAAAIAAABIAAgBAADAoIgDASIALgNIgIgF").cp();

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.lf(["#996600","#FFCC00"],[0.529,1],3.8,-4.9,1.2,0.1).s().p("AgvgDIABgBQAIgCAEgGQAHADAPABQAVAAAHAAQAOAAAJAHQACABAHAAQgGAIgHAFQAAAAAAAAQgegDgYgHQgQgDgMgDIAAAA").cp();
	this.shape_105.setTransform(-15.6,3.7);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#FFCC00").s().p("AABAAIAAAAQgBAAAAAAIAAAAQAAAAABAAIAAAA").cp();
	this.shape_106.setTransform(-7.8,2);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.lf(["#996600","#FFCC00"],[0,1],0,-1.7,-1.2,3.8).s().p("AAdgIIAAgBQAAgCgCgDQAAAAgCgBQAJABAEADQADADAAAAQACABADAAQAAABAAABQgJgCgIgBIAAAAAAmAQQgHgBgCgCQgJgHgOAAQgGAAgXAAQgPgBgHgEQAEgDABgHQAKACAGAAQAFAAAFgBQAAAEAGADQAHACAIAAQAAAAAAAAQAHAAAEgBQAGABAHABQAHACAFACQgBADgCADIAAgBQgBADgBACIAAAA").cp();
	this.shape_107.setTransform(-14.6,2.1);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.lf(["#FEFDAB","#FFFF00","#FFCC00"],[0,0.235,1],-0.3,-1.3,0.9,2.4).s().p("AgJAZQgFABgFAAQgGAAgKgCQABgCgBgCQAAgQgKgJQgCgDgDgBQALgEAPgEQAUgFAVgDIABABQASAGAIASQAHAMAAAOQgDAAgCgBQAAAAgDgDQgEgDgIgBQgBgBgCgBQgHgDgJAAQgKAAgFADQgGADAAAFIAAAB").cp();
	this.shape_108.setTransform(-15.1,-1.3);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.rf(["#FEB4B4","#FF0000","#430101"],[0,0.282,1],-1.7,-0.4,0,-1.7,-0.4,7.5).s().p("AATASQgEAGgIADIAAAAQgegMAAgPQAAgOAfgMIABAAQACAAACADQAKALABAOQAAACAAACQgBAHgEAFIAAAA").cp();
	this.shape_109.setTransform(-21.1,0.4);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#AAAAAA").s().p("ABGAEIAAAAIgBgDQgBgBAAAAIAAAAQgBAAAAAAIAAAAQAAAAAAgBQgBgBgBgBQgBgBgBgBIgBAAQgDgBgCAAQgFAAgCABQgBACAAADQAAABAEAGQgBAAgBAAQgFgBgBgCQgDgDAAgBQAAgEAEgDQAEgEAKAAQAEAAAFABQADABACABQABAAABACQAAAAAAABQAAABAAABQAAADgGAEIAAAAAgBADQABABADACQADABAEACQgDABgDAAIAAAAQgBAAgBAAQgDgBgEgDQgEgDAAgDQAAgFAEgBQAFgEAFAAQAFAAAGADQAFACABACQAAABAAAAQAAABAAABIAAAAQAAABgCACQgCgCgCgBQgBAAAAAAQgJgFgCAAQgEAAgBADQgEABAAABQAAABAEACIAAAAAhEABQAAACAAAAQAAACABABQABAAACABQAAABABAAQAFABAGABQgEADgHAAQAAgBAAABQgMgCAAgGQAAgEAEgCQAGgEAJAAQAIAAAFADQACACAAABIAAAAQgFgBgEAAQgCAAgCAAQgCAAgDAAQgDAAgEAAQgBABgBAAIAAAA").cp();
	this.shape_110.setTransform(-7.4,1);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.lf(["#996600","#FFCC00"],[0.529,1],1.5,-6.2,0.4,0.1).s().p("ABegEQgSgBgIAAQgZAAgoAEQgzACAAAHQAAACAFAEQgcgBgZgDIAAAAQAHgFAFgGQAGABAFAAQAMAAAGgBQAJgDALgCQAKgCAQAAQARABALAAQAOAAAQgDQAPgDAWAAQAFAAAGAAQgBAFgCAEIAAAA").cp();
	this.shape_111.setTransform(-2.1,4);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#006600").s().p("AhYgBIAAAAQAAgCAGgDQAGgDAMgDQAhgIAzAAQAmAAASAEQAAAAAAABQABAAAAAAIAAAAQAAABgBAAIAAAAQgRgFgnAAQgzAAggAIQgLACgHAEQgGACAAACIAAAAIAAAAIgBAAABXAIQgUgDgUABQgKAAgWAEQgDAAgSADQgLACgCAFIAAABIgBAAQAAAAAAgBQgBAAAAAAQADgGAMgCIgBAAQASgDAEgBQAWgDAKAAQAUgBAUADIABAAQABAAAAABIAAAAIAAAAQgBAAgBAAIAAAA").cp();
	this.shape_112.setTransform(4.9,7.1);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#333333").s().p("Ah8ADQgHgBgEgCQgBAAgBAAQgCAAgBAAQgBAAAAgCQAAgBABgBQAAAAAAABQABAAAAAAIAAABQAAAAAAABQAEABAFAAIAAAAIABAAQAGAAAFABQAFACAFABQABAAAAABIAAAAQAUAGAWgBQAlgDAjgEQAWgCAWgBQAHAAAIAAQANAAANAAQASAAATAAQACAAADgBQABgBACgBQABAAABAAQABgBACAAQgBACgBACQgDABgHAAQggABgRAAIAAAAQgBAAAAAAIgBAAQAAAAAAAAIgBAAQgfABgVABQg0AEg2AFQgEAAgOgDIABAAQAAAAgBAAQAAgBAAAAIgBAAQAAAAAAABQgGgCgGgBQgHgCgGgCIAAAAAgEgIQABABAAAAQAAABAAAAIAAAAQABABAAAAIABADIABAAQAAABAAAAQgBAAAAAAQgBAAgBAAQAAAAgBgBQAAgBgBAAQAAAAAAgBQAAAAgBAAIAAgBIAAgBQAAAAgBAAIAAgBIAAAAIAAgBQgBgBAAAAQAAgBgBAAIAAAAQAAgBAAAAQAAAAAAgBIAAAAQAAAAABAAIAAAAIAAABIABAAQAAAAABABIABAAQAAABABABIAAAAAg6ADQgBgBgCgBQgDgBgDAAQgEgBgDgCQgBgBgBgBIAAAAQAAgBAAAAIAAAAQABAAAAAAIABAAQAAAAABABQABAAAAAAQACABACABQACACACAAQAAABAAAAQAEAAADAAQABAAAAABIABAAQAAABAAAAIgBAAQAAAAAAABQgBAAAAAAIgBAAAh0AEQAAAAgBAAQAAAAAAAAQABABABAAQAAgBgBAAIAAAAAh5ADQAAAAABAAQAAAAgBAAQgBgBgBAAQABABABAAIAAAAAh2AEQgBAAgBgBIABABQABAAAAAAIAAAA").cp();
	this.shape_113.setTransform(-0.2,1.7);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#FFFFFF").s().p("ACEAUQABAAAAAAQAAAAABABQAAABAAABQAAADgBACQgUABgVACQAAAAgBAAIAAAAQgBgBgCAAQg4AEg2AEQglAIgngGQAAAAgBgBQgBAAgBgBIAAgBQgBAAAAAAQgDgBgCAAQAAAAgBgBIAAAAQgGgBgGgBQgCgBgCAAQgBAAAAgBIgBAAIAAAAQgBAAgCAAQgDgBgBgBIAAAAQAAgBABAAQAAAAAAAAIABAAQACAAAAAAQANABALADQACABABAAQABAAABABIACAAQAAAAABABQACAAAAABIAAABQAXAEAXgDQgBAAAAgBQgCgBgCgCQgBAAAAAAIAAgBQgBAAAAAAQgBgBgCAAQgBgBgCAAIgBgBQAAAAAAAAQAAgBgBAAQAAAAgBAAQgBgBgBAAQgBgBAAAAQABgBABAAQAAABABAAQAAAAABAAQAGABAFADQAEABADABQAAABABAAIABABQABAAAAABQABAAAAABIAAABQAEgBAEgBQAMgCALgBQAAAAAAgBQAAAAgBgBQAAAAgBgBQAAgBAAgBQAAgBABgBIgBAAIAAgBQAAgBAAgBIAAAAQABABABABQAAABABAAQAAABAAABQAAACAAABIAAAAQAAABAAABQAHgBAFAAQATgBARgCQATgBASgBQAKgBAKgBQAQgDARgDQABAAABAAQAAAAABAAIABABAgKgjQgJABgPACQgBAAgQAEQgPAFgDAAQgDAAgDgBQgDgBAAgCQAAgGATgFQAQgEAQAAQAFAAAFABQACABAEADQAAABABABIAAAA").cp();
	this.shape_114.setTransform(-0.3,-1.6);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#CCCCCC").s().p("ACMgGIgBAAQgBAAgBAAQgBAAgBAAQgQACgRADQgJABgLAAQgSABgSABQgSABgSABQgHABgFAAQAAgBAAAAIAAgBQAAgBAAgBQAAgBAAAAQgBAAgBgBQgBgBAAgBIgBABQAAAAABABIAAABIAAAAQAAAAAAABQAAABAAABQAAAAABABQAAAAABABQAAAAAAABQgMABgLACQgEAAgEABIAAgBQgBAAAAgBQgBAAgBgBIgBAAQAAgBgBAAQgDgCgDgBQgFgCgHgBQAAAAgBAAQAAAAgBAAQgBAAAAAAQAAAAABABQABAAABABQAAAAABAAQAAAAAAAAQABAAAAABIAAAAQACAAACABQABABABABQABAAABAAIAAAAQAAABAAAAQADABABABQABABABABQgYACgXgEIAAAAQAAgBgBgBQgBAAgBgBIgBAAQgCAAgBAAQgBgBgBAAQgMgDgMgCQgBAAgBAAIgBAAQAAABgBAAQAAAAAAAAIAAABQABABADAAQABAAABAAIABABIAAAAQABAAAAAAQACABACAAQAGABAGACIABAAQAAAAABAAQACABACAAQABAAAAABIAAAAQABABABABQABAAAAABQAnAFAmgIQA2gEA4gDQABAAABAAIABAAQAAAAABAAQAUgBAUgCQACAAgBgCQAAgCAAgBQAAAAgBAAQAAgBAAAAIAAAAAiDABQAAgBACAAQAEgBACAAQADAAACAAQACABACAAQAEAAAGABQAHABAJACIABAAQAAABABAAIAAAAQABAAACAAQAJACAGABQACABABAAQAFABACAAQAEAAAFgBIABAAQAAAAABAAQAAAAAAAAIABAAQAAgBAAAAIgBgBQAAAAgBAAQgDgCgEgBQAAAAAAAAQgCgBgCgBQgCgBgCgBQAAAAgBAAQgBAAAAAAIgBAAQAAAAgBAAIAAAAQAAAAAAAAIAAAAQABABABABQgDgCAAAAQAAgCAEgBQADgCAEAAQACAAAIAFQABAAAAAAQACABACABQAGAEAEACQAJgBAMgBQgGgBgEgCQgEgDgCgBQAAgBAAgCQAAgFAGgDQAGgEAJAAQAHAAAGAEQACABACACQgCgBgDgBQgFgBgDAAQgJAAgFAEQgDADAAAFQAAABADACQABACAFABQABAAABAAQgFgFAAgCQAAgDACgBQABgCAFAAQADAAACABQAAAAAAABIAAAAQAAAAAAABQAAAAAAAAIAAABQAAAAAAAAQAAABAAAAIAAABIAAAAIAAABQABAAAAAAIAAAAIAAAAQABABAAAAQAAAAAAABQABAAAAABQABAAAAABQABAAABAAQAAAAABAAQALgBANgCQAggBAXgDQABABAAAAQABAAAAgBQAAAAAAAAQAbgDANgCIADgBQAHgBAFADQAFACACAEQABABgBABQgBAAgCAAQAAAAgBABQgCAAgCACQgCAAgDAAQgSABgTAAQgNAAgMABQgIAAgIAAQgWABgWACQgiAEglADQgWACgUgHIAAAAQAAAAgBAAQgFgCgFgBQgFgCgGgBIgBAAIAAAAQgFAAgEgCQAAAAAAgBIAAAAQAAAAgBgBQAAAAAAAAIAAAAAhBAJIAAAAQgCAAgBgBQgEgBgEgCQgDgCgCgCQgBgBAAgBQAAgGAGgDQAGgEAJAAQAJAAAGAEQAFADABADQgBgCgFgCQgGgDgFAAQgFAAgHAEQgDABAAAGQAAACAEADQAEADAFABQgBAAgBAAQgCAAgCAAIAAAAAAAgFQABAAABABIgBAAQgBAAAAgBIAAAAIAAAAAAEAAQAAgBgBgBQABABAAAAIAAABAhqgDQgGgDgIAAQgJAAgFAEQgFACAAAEQAAAGAMACQgJAAgHgEQgGgDgBgEIAAgBQAAgDAHgDQAHgDAJAAQAJAAAHADQACABABABQABABABAAIAAAAAhtAKIAAABQAAAAgBgBIgBAAQABAAABAAIAAAAAhwAJQgBAAgBAAQABAAABAAQABABAAAAQgBAAAAgBIAAAAAhrALQABAAAAAAQgBAAgBAAQAAAAAAAAQABAAAAAAIAAAA").cp();
	this.shape_115.setTransform(-1,1);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.lf(["#996600","#FFCC00"],[0.529,1],-1,-1.6,0.2,0).s().p("AAFgEQACABABAAQAEABADABQgTADgKADQAAgDAAgCIAAAAQAEAAAHgBQADgCADAAQABAAABgBIAAAA").cp();
	this.shape_116.setTransform(24.2,-6.2);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.lf(["#996600","#FFCC00"],[0,1],-1.2,0.3,2.3,0.3).s().p("AgCgDQAFACAJABQgCAAAAAAQgFAAgDABQgFACgEABQgBgEgDgDQABAAAAAAIAIAA").cp();
	this.shape_117.setTransform(23.6,-6.6);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.lf(["#FEFDAB","#FFFF00","#FFCC00"],[0,0.235,1],-0.3,-0.9,0.5,1).s().p("AgYAHIgIAAQAAAAgBAAQgFgFgKgDQgCgBgBgBQAEgBAFAAQADgBAFAAQAMgBARAAQARAAATACQAHABAEABQACABABAAQAGABABAAQgBAAgBAAIgBAAQgDAAgKAAQgJAAgEAAQgMAAgRAAQgaABAAACQAAABACABQACABAEABIAAAA").cp();
	this.shape_118.setTransform(25.8,-7.8);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#339900").s().p("ACqhAQgCAAgBgBQgFgBgGgBQgUgCgSAAQgSAAgLABQABgIAPgOQAQgQAVgEQASgEARAEQAPAEAIAHQAIAIgGAFQgGAGgaAQIAAAAAB8gvQgDgBgEgBQgBAAgCgBQgJgCgHgCQgEgBgCgBQgCgBAAgBQAAgCAagBQATgBANAAQAEAAAJAAQAKABACAAIABAAQACAAABAAQAAABABAAQABAAAAAAQADABACABQAIAGAAAEQAAACgQACQgMABgJAAQgFAAgLgCQgFgBgEAAQgDgBgDAAIAAAAAgHBFQgRgEgmAAQg1AAghAIQgMADgGADQgGADAAACIAAAAQgIgDgHgEQgHgEgEgCQgFgEAAgDQAAgHA1gEQAngDAaAAQAIAAASABIAAAAQAAABAAAAQABAAAAAAQAAgBABAAIAAAAQATABAFACQABAAABAAQAEABAEACQAHADAFAFQACACACACIAAAAAhpBrQgVgGgWgIQgKgDgIgDQAAgBgDgBQgBAAgBAAIAAgBIAAAAIAAAAQAAgCAGgCQAHgEALgCQAggIA1AAQAmAAARAFIABAAQAIAMABALQgSgDgUABQgKAAgWADQgEABgUADIABAAQgMACgDAGIAAAAAhnBrQACgFALgCQAUgDADAAQAWgEAKAAQAUgBASADQAAABAAABQAAAHgeAFQgZAEgRAAQgKAAgSgEQgDgBgDgBIAAAA").cp();
	this.shape_119.setTransform(13.3,-1.5);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.lf(["#996600","#FFCC00"],[0.529,1],-5.9,-4.6,1.3,0).s().p("AgUAfQgEgCgEgBQgBAAgBAAQgFgCgTgBQACgFABgEQAEAAAGABQAPACAGAAQALAAAJgEQAEgDAIgEQAGgDAIgDQAFgCAAgDQgCgIAAgBQAAgGAIgDQAKgFAEgEQAEAIAAAJIAAAAIABAAIgVAUQgNANgnAKQgBABgCAAIAAAA").cp();
	this.shape_120.setTransform(13.1,1);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.lf(["#FEFDAB","#FFFF00","#FFCC00"],[0,0.235,1],-0.2,-0.7,2.5,1.8).s().p("AAZgVIAAAAQACABACABQAJAEAFAFQgUACAAAEQAAABACACQACABAAAAQAAADgOADQgNADAAACQAAAGAAACQgBACgDABQgDgDgEgEQgPgLgQgEQAFAAAFgBQAngNAIgEQAFgBAFgCIAAAA").cp();
	this.shape_121.setTransform(17.8,-5.9);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.lf(["#996600","#FFCC00"],[0.529,1],-6.1,-2.4,0.1,-0.6).s().p("AAUgbQAAADAAADIAAAAIgBAAQgBABgRAWQgMAUgEAGQAAgIgEgIQAAAAAAgBQACgCAEgIQAEgEAGgEQAIgHACgBQABgBADgFQADgDACgBQAAgBAEgBIAAAA").cp();
	this.shape_122.setTransform(20.4,-3.4);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.lf(["#996600","#FFCC00"],[0,1],-2.6,0.9,2.7,0.9).s().p("AgOAYQgDgIgHgHQACgBABgCQABgCAAgEQAAgCAOgDQAMgDAAgCQAAgBgCgCQgCgDAAAAQAAgEAUgDIAAABQADAEABAEQgEABgBABQgBABgDADQgEAFgBABQgBABgLAFQgEAEgDAGQgEAHgDADIAAAA").cp();
	this.shape_123.setTransform(19.9,-4.6);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.lf(["#996600","#FFCC00"],[0,1],-5.4,0.6,5.8,0.6).s().p("AgyAJQAAgDgCgDQAHgBAGgCQAKgDAGAAQACAAAOABQAKAAAFgEQACgCAEgJQAGgMASgCQACAAACgBQAHAIAEAHIAAABQgFAEgKAEQgIAEAAAEQAAABADAIQAAAFgGACQgHADgHADQgHAEgGADQgHAEgMAAQgFAAgQgCQgFgBgFAAIAAAAQABgEAAgDQASAAAfgBQAGAAADgDQABgCAAgCQABgBgBgCQgCgEgFgDQgDgCgHAAIgDABQgNACgbADIAAAA").cp();
	this.shape_124.setTransform(12.9,-0.3);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.lf(["#FEFDAB","#FFFF00","#FFCC00"],[0,0.235,1],-1,-1.9,1.1,1.9).s().p("AgsgTQAIAAAIgBQAdgEAUgEIABAAQAQAEAOAMQAEADADADQgCABgCAAQgRACgGAKQgEAKgDACQgFADgMAAQgLgBgCAAQgHAAgJAEQgHADgGABQgDgKgHgKQgDgEgHgGQgCgDgCgCIAAAAQACAAABgCQALgGAAgEQAAgBAAAAIAAAA").cp();
	this.shape_125.setTransform(11.1,-2.9);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.lf(["#996600","#FFCC00"],[0,1],-0.5,-1.3,-0.5,5.7).s().p("AALAAQAAAAAAgBQAGgDAAgFQAAgBAAgBQADgCAMgEQAQgEAHAAQAFAAAKACQAHACABACQABABAFAAQACAAADAAQAAADABACIAAABQgXACggAEQgNABgLABIAAAAAgmgBQADgDAAgCQABAAAAgBQACAAAFAAQACAAACABQACADAEACQAEABAGAAQgMABgJABQgEgBgGgCIAAAAAgwACQACABABABQgFAAgEAAQgCAAgFAAIAAgBQACABACAAQABAAABAAQAAgBABAAIABAAQADAAACgBIAAAAAhNgDQACADADAAQAEACAEABIAAAAQgGgBgJgCQgCAAgBAAIAAAAQAAAAAAgCQACAAADgBIAAAAAhaAVQACgBABgDQABgDABgDQAOADAEAAQA2gFA0gEQAVgBAegBIABAAQAAADgBAEQgGgBgFAAQgWAAgPADQgQADgNAAQgMAAgRAAQgQgBgJACQgMADgJACQgFABgNAAQgEAAgGgBIAAAA").cp();
	this.shape_126.setTransform(-1.4,1.6);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.lf(["#FEFDAB","#FFFF00","#FFCC00"],[0,0.235,1],-0.7,-2.3,0.9,2.4).s().p("Ag/AaQgDABgCAAQAAgOgHgNQgJgRgRgHQAHgBAIgBQgCACAAABQgBACAEADQAGADAKADQAaAIAigBQAjAAAdgHQAPgEAIgEQACACACACQAHAIADAEQAHAIADAKQgDAAgCAAQgFAAAAgBQgBgBgHgCQgLgDgFAAQgHAAgPAFQgNADgDADQAAgBAAgBQgBgBgBgBQgBgCgDgBQgGgEgJAAQgIAAgFAEQgGADAAAFQAAACABABQgDAAgCAAQgEAAgCAAQgBAAgBAAIAAAAQAAgBAAgBQAAAAAAgBQgBgDgFgDQgHgEgIAAQgJAAgGAEQgGADAAAGQAAACABACIAAAA").cp();
	this.shape_127.setTransform(-2.8,-1.4);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#537DBD").s().p("AAAAJQABgEABgBQAAgBAAgEQAAgEgBgEQALgCAJAAQAOAAAJAHQgJAFgZAGQgGABgEABIAAAAAghAMQgDgBgDgBQgEgDAAgCQAAgFAZgFQADgBAEAAQAAAAAAACQADAEAAADQAAADAAAAQgBABgDAEQgLABgKAAIAAAA").cp();
	this.shape_128.setTransform(0.2,-4.1);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f("#012343").s().p("AAHgOQAIAEACAIQABACAAAEQAAAFAAABQAAACgCADQgHABgGABQADgEAAAAQAAgBAAgDQAAgEgCgFQgBAAAAAAQgBgCgCgCQAAgBAAAAQgEgDgCgCQgBgBgBgBQgFgDgEgBQAMAAAMACIAAAA").cp();
	this.shape_129.setTransform(-1.4,-4.8);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#CC6600").s().p("AAdAPQABADAAADQABABgBAAQAAAAAAAAQgBAAAAAAIAAgBQgBgCgBgDQgDgLgHgHQgDgFgHgHQgCgDgCgCQAAAAAAAAIABAAQAAgBABABIAAAAQACACACACQAHAIADAEQAHAIADAKIAAAAACMALIgBAAIAAAAQAAgJgEgGIAAAAQgDgIgIgHQgDgEgEgDQgOgLgQgFIgBAAIAAAAIABgBIAAAAQABABAAAAQAQAEAPAMQAEADADADQAHAHAEAIQAAAAAAAAQAEAGAAAIQAAABAAABIAAAAIgBAAACygnIAAAAQAAgDAAgDQgBgEgDgEIAAgBQgEgFgJgEQgCgBgCgBIgBAAIAAgBQABAAAAAAIABAAQACABACABQAJAFAFAFQADAEABAFIAAAAQAAADAAACIAAABQAAAAgBAAIAAAAQgBAAAAAAIAAAAAiTArQgBADgBADQgBADgCABQgFAJgHAEQAAABgBAAQgBAAAAgBIgBAAQAAAAABAAQAHgFAFgIQACgCABgCIAAAAQACgDABgDQAAgBAAAAIABAAQAAAAAAABQABAAAAAAIgBAAAiQAcQAAACAAABIAAAAIAAAAQAAAAgBAAIgBAAQAAgBAAgCQAAgOgGgNQgJgQgSgGIAAgBQAAAAAAAAQAAgBABAAIAAAAQABABAAAAQASAGAJARQAGANAAAOIAAAAAAfAqQgBAEgCAFIAAAAQgBAAAAABQAAAAgBAAQAAAAAAgBIAAAAQACgFABgEQABgEAAgDQAAAAAAAAIABAAQAAAAABAAIAAAAQAAADgBAEIAAAA").cp();
	this.shape_130.setTransform(4.7,-1.5);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.f("#000000").s().p("Ag5gvQgOgCgMABQgCAAgCAAQgPAAgMADQgQAEgJAGQgCABgCACQgRADgGAFQgHABgIABQAAAAgBgBIAAAAQgBAAAAABQAAAAAAAAQgXADgVAFQgOAEgLAEIgBAAQghAKAAAQQAAAQAgAMQALAEAQAEQAaAHAeADIABAAQAAABABAAQAAAAAAgBIABABQAZACAbACQAEACAIAEQAGAEAIADIABAAIABABQAAAAABAAQAEABAAABQAIADAJADQAXAIAVAGQAAAAAAAAQAAABABAAIAAAAIABgBQADABACABQAQAEAKAAQARAAAZgEQAhgFAAgHQAAgBAAgBQAAAAABAAIAAAAIAAAAQAAgBgBAAIAAAAQgBgLgLgMQABAAAAgBIAAAAQAAAAgBAAQAAgBAAAAQgCgCgCgCQgFgFgHgDQABAAABgBQAqgKANgNIAUgWIABAAIABAAQAAgBAAgBQADgFAPgSQAQgYACgBIAAAAQABAAAAAAIABAAQAAAAAAAAIAAgBQALgDAVgEQADAAADABQAEAAAEABQALACAGAAQAJAAALgBQARgCAAgCQAAgEgIgGQgCgBgEgBQAAAAAAAAQgBAAgBgBQgBgBgGgCQAagQAHgGQAFgFgIgIQgIgHgPgEQgRgEgRAEQgVAEgRAQQgOAOgCAIQgFAAgDABQgFAAgEABIgBAAQgBAAAAAAIAAABQgFACgFACQgIADgpANQgEABgFACQgBAAAAgBIgBAAIAAABIAAAAQgUAFggADQgHABgJAAQgBgBgFgBQgFgBgOAAQgCgBgDgBQgLgEgQgDQgHgBgHgBIAAAAAgHgrQAOAAAGACQADAAADABQAFAAAEgBQAegDAUgEQAFgCAEgBQAogMAHgDIAAAAQAGgDAHgCQAGgCAGgBQABAAABAAQAEgIAMgLQATgSAYgFIAAAAQAWgFAWAFQATAFAKAJQAMALgKAIQgFAGgUAMQADABADACIAAAAQALAIAAAGQADAHgeADQgNABgJAAQgHAAgNgCQgFAAgEgBQgBAAAAAAQgTAEgJACQAAABgBAAQABABgOAUQgQAVgDAEQgBABAAAAIgVAWQgMANgjAKQABACACABQACADACACQAMAPABANQAAABAAABQADAMgtAGQgaAEgTAAQgLAAgUgEQgDgBgDgBIgBAAQgWgGgXgIQgKgEgJgDQgBAAAAgBQgBAAgBAAQgBgBgBAAIAAAAQgBgBAAAAQgJgDgGgEQgGgDgEgCQgagBgXgDQAAAAgBAAIAAAAQgggEgcgHQgQgEgNgFIAAAAQgmgOABgTQgBgSAngNQAAAAAAAAIABAAIAAgBQAMgEAPgEQAWgFAZgEQAGAAAGgBQAHgEAPgEQABgBACAAQAKgHASgFQAPgDARgBQACAAACAAQAOAAAQACQAHABAHABQASADANAEQABABABAAIAAAAAELhCIgBAAQABAAAAAAQABAAABABQgBgBgBAAIAAAAAh/AjIAAAAIAAABIAAgB").cp();
	this.shape_131.setTransform(5.1,-1.5);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.f("#99CCFF").s().p("AAbgDQgCgIgIgEQAHAAAHACQAQACALAFQADAAACABQAFACACACQABAAAAABIABAAQgBAAAAAAQgKgFgNAAQgKAAgLACIAAAAAANgBQgDABgDAAQgXAFAAAGQAAACAEACQADACADABQgCAAgCAAQgRAAgUgDQgZgFACgHIAAAAQABgDACgBQACgBACgCQAJgFAQgEQAMgDAPgBQACAAACAAQAEABADADQABABABABQgCAAgFAAQgQAAgQAEQgTAEAAAFQAAABADACQADABADAAQACAAAPgFQAQgCABAAQANgDAKgBQACACABACIAAAA").cp();
	this.shape_132.setTransform(-2.4,-4.7);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.f("#FF0000").s().p("ABMAAQgJAFgPADQgcAHgjABQgjAAgagHQgJgDgGgEQgFgCABAAQABgCABgBQAGgFARgDQgCACgBADIAAABQgCAFAZAEQAUADARAAQACAAACAAQAIAAALgBQAGgBAHgBQAFgBAFgBQAZgEAKgHQAAgBABAAIgBAAQAAgBgBgBQgCgCgFgBQAQAAAFABQAFABABABQABABAAAAQAAAEgLAHQgCAAgCAAQAAAAgBAAIAAAAQgBAAABAAIAAAA").cp();
	this.shape_133.setTransform(-2.5,-3.6);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.f("#FFFF00").s().p("ABwgNIAOCFIhZhyIjyByICWh2Ij0AQIDvgrIhihaICMBBIAOhDIAMA3ICqg5IhsBNIDmAhIi8gE").cp();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]}).to({state:[{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40}]},1).to({state:[{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57}]},1).to({state:[{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72}]},1).to({state:[{t:this.shape_133},{t:this.shape_132},{t:this.shape_131},{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105}]},1).to({state:[{t:this.shape_134}]},1).to({state:[]},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21.2,-12.4,60,24);


(lib.AAGun = function() {
	this.initialize();

	// Layer 1
	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.lf(["#06A5E8","#00121A"],[0,0.859],-4.9,-0.8,11.7,2.3).s().p("AgoApIAAgnIAAgUIAigWIAAAcIAvAAIAAAOIgTAoIg+AAIAAgB").cp();
	this.shape_135.setTransform(-7.5,35.3);

	this.shape_136 = new cjs.Shape();
	this.shape_136.graphics.lf(["#63CDFA","#016B98"],[0,0.863],2.3,-0.7,6.9,-1.8).s().p("AA4grIAAAmIhwAxIAAgPIBwhI").cp();
	this.shape_136.setTransform(-17.3,40);

	this.shape_137 = new cjs.Shape();
	this.shape_137.graphics.lf(["#06A5E8","#94DDFC","#06A5E8","#014E6D","#06A5E8"],[0.051,0.204,0.353,0.761,1],-1.3,0,1.5,0).s().p("AgGgHIANAAIAHAAIAAAPIgbAAIAAgPIAHAA").cp();
	this.shape_137.setTransform(-2.8,23.1);

	this.shape_138 = new cjs.Shape();
	this.shape_138.graphics.lf(["#06A5E8","#94DDFC","#06A5E8","#014E6D","#06A5E8"],[0.051,0.204,0.353,0.761,1],-0.6,0,0.8,0).s().p("AAHA5IgNAAIAAhxIANAAIAABx").cp();
	this.shape_138.setTransform(-2.7,16.5);

	this.shape_139 = new cjs.Shape();
	this.shape_139.graphics.lf(["#06A5E8","#94DDFC","#06A5E8","#014E6D","#06A5E8"],[0.051,0.204,0.353,0.761,1],-0.6,0,0.8,0).s().p("AAHAHIgNAAIAAgNIANAAIAAAN").cp();
	this.shape_139.setTransform(-2.7,1.9);

	this.shape_140 = new cjs.Shape();
	this.shape_140.graphics.lf(["#06A5E8","#94DDFC","#06A5E8","#014E6D","#06A5E8"],[0.051,0.204,0.353,0.761,1],-1.4,0,1.5,0).s().p("AAIAoIgNAAIgJAAIAAhPIAJAAIANAAIAHAAIAABPIgHAA").cp();
	this.shape_140.setTransform(-2.8,6.7);

	this.shape_141 = new cjs.Shape();
	this.shape_141.graphics.lf(["#06A5E8","#00121A"],[0,0.859],1.9,-1.8,-5.8,-1.7).s().p("Ag3gFIAAgmIBvBIIAAAPIhvgx").cp();
	this.shape_141.setTransform(18.2,40);

	this.shape_142 = new cjs.Shape();
	this.shape_142.graphics.lf(["#63CDFA","#016B98"],[0,0.863],-7.4,0,7.6,0).s().p("AhKgMICVAAIAAAZIiVAAIAAgZ").cp();
	this.shape_142.setTransform(0.4,44.7);

	this.shape_143 = new cjs.Shape();
	this.shape_143.graphics.lf(["#63CDFA","#016B98"],[0,0.863],-0.5,-0.7,-0.4,-4.5).s().p("ABLAmIiVAAIASglIASgmIBNAAIATAmIARAl").cp();
	this.shape_143.setTransform(0.4,39.4);

	this.shape_144 = new cjs.Shape();
	this.shape_144.graphics.lf(["#06A5E8","#00121A"],[0,0.859],0.3,6.2,0,-1.5).s().p("AAnAHIhNAAIAAgNIBNAAIAAAN").cp();
	this.shape_144.setTransform(0.4,34.8);

	this.shape_145 = new cjs.Shape();
	this.shape_145.graphics.rf(["#06A5E8","#00121A"],[0,0.859],1.7,1.4,0,1.7,1.4,2.2).s().p("AgLAFQABAAAAABQAEACAFABQADgBADgCQAEgFAAgCQAAgFgEgEQgBAAAAAAQACAAACACQAEADAAAFQAAAEgEAEQgEADgEAAQgFAAgDgDQgBgCgBAAQAAgBgBAAIAAAA").cp();
	this.shape_145.setTransform(0.7,30.8);

	this.shape_146 = new cjs.Shape();
	this.shape_146.graphics.rf(["#06A5E8","#00121A"],[0,0.859],1,1.3,0,1,1.3,4.4).s().p("AgIAHQABABAAAAQABABABABQADAEAEAAQAEAAAEgEQAEgDAAgFQAAgEgEgDQgCgCgBgBIgBAAQgDgCgDAAQgEAAgDADQgDAEAAADQAAAEACADIAAAAAAQgQQAIAHAAAJQAAAKgIAHQgGAHgKAAQgJAAgHgHQgHgHAAgKQAAgJAHgHQAHgHAJAAQAKAAAGAHIAAAA").cp();
	this.shape_146.setTransform(0.4,30.5);

	this.shape_147 = new cjs.Shape();
	this.shape_147.graphics.lf(["#63CDFA","#016B98"],[0,0.863],-0.1,-0.4,0.7,6.9).s().p("AglAjIgxAAIAAgdIAAgNQAEgDAEgDQAfgVAqAAQADAAACABQAAgBAAABQABgBAAABQADgBADAAQAqAAAeAVQAEADAEADIAAANIAAAdIgwAAIhMAAAAHgHQAAAAABABQAEADAAADQAAAFgEAEQgDADgFAAQgDAAgDgDQgBgBAAAAQgDgDAAgFQAAgDAEgDQADgDADAAQADAAADACIABAAAARgPQgHgIgKAAQgJAAgHAIQgHAHAAAIQAAAKAHAHQAHAIAJAAQAKAAAHgIQAHgHABgKQgBgIgHgHIAAAA").cp();
	this.shape_147.setTransform(0.4,30.4);

	this.shape_148 = new cjs.Shape();
	this.shape_148.graphics.lf(["#06A5E8","#00121A"],[0,0.859],3.7,0.6,-5.3,-0.1).s().p("AApACIAAAnIAAABIg+AAIgTgoIAAgOIAuAAIAAgcIAjAWIAAAU").cp();
	this.shape_148.setTransform(8.4,35.3);

	this.shape_149 = new cjs.Shape();
	this.shape_149.graphics.lf(["#06A5E8","#00121A"],[0,0.859],0,0,0,7).s().p("AgtgLIAdAAIAgAAIAeAAIAIAAIAAAWQgVgGgaAAQgDAAgCAAQgBAAAAAAIAAAAQgBAAAAAAIAAAAQAAAAAAAAQgCAAgDAAQgaAAgWAHIAAgXIAIAA").cp();
	this.shape_149.setTransform(0.3,25.2);

	this.shape_150 = new cjs.Shape();
	this.shape_150.graphics.lf(["#06A5E8","#94DDFC","#06A5E8","#014E6D","#06A5E8"],[0.051,0.204,0.353,0.761,1],-1.3,0,1.5,0).s().p("AAOAIIgbAAIAAgPIAHAAIANAAIAHAAIAAAP").cp();
	this.shape_150.setTransform(3.5,23.1);

	this.shape_151 = new cjs.Shape();
	this.shape_151.graphics.lf(["#06A5E8","#94DDFC","#06A5E8","#014E6D","#06A5E8"],[0.051,0.204,0.353,0.761,1],-0.6,0,0.8,0).s().p("AAHA5IgNAAIAAhxIANAAIAABx").cp();
	this.shape_151.setTransform(3.4,16.5);

	this.shape_152 = new cjs.Shape();
	this.shape_152.graphics.lf(["#06A5E8","#94DDFC","#06A5E8","#014E6D","#06A5E8"],[0.051,0.204,0.353,0.761,1],-1.4,0,1.5,0).s().p("AAHAoIgNAAIgIAAIAAhPIAIAAIANAAIAIAAIAABPIgIAA").cp();
	this.shape_152.setTransform(3.4,6.7);

	this.shape_153 = new cjs.Shape();
	this.shape_153.graphics.lf(["#06A5E8","#94DDFC","#06A5E8","#014E6D","#06A5E8"],[0.051,0.204,0.353,0.761,1],-0.6,0,0.8,0).s().p("AAHAHIgNAAIAAgNIANAAIAAAN").cp();
	this.shape_153.setTransform(3.4,2);

	this.shape_154 = new cjs.Shape();
	this.shape_154.graphics.f("#000000").s().p("AA4jQIAABRQAAAFgDADQgCACgCABIAABdQACABACABQADAEAAAFIAAAFQACABADACQAEAEAAADIAAAcQALAFAKAHQAFAEAEADQACACABACQABADAAACIAAAJIAcATQADABACADQABADAAADIAAAQIBsBGQADABACADQABACAAAEIAAAPQAAAEgCADQgDAEgFABQgDABgEgCIhtgxIgsAAIAJAVQABACAAADIAAAcQAAAFgDAEQgDADgGAAIiVAAQgFAAgEgDQgDgEAAgFIAAgcQAAgDABgCIAKgVIgsAAIhuAxQgEACgDgBQgFgBgCgEQgDgDAAgEIAAgPQAAgEACgCQABgDADgBIBshGIAAgQQAAgDACgDQABgDADgBIAcgTIAAgJQAAgCABgDQABgCACgCQAEgDAFgEIAAAAQAJgGAKgEIAAgfQAAgDAEgDQACgDACAAIAAgGQAAgEAEgEQACgCACAAIAAhdQgDgBgCgCQgEgEAAgFIAAhQQAAgFAEgEQACgCADgBIAAgDQAAgEADgEQADgEAGAAIAOAAQAFAAADAEQAEAEAAAEIAAAEQACABACABQADAEAAAFIAABQQAAAFgDAEQgCABgCABIAABeQACAAACACQADAEAAAEIAAAGIAIAAIAAgFQAAgFAEgEQABgBACgBIAAhdQgCgBgCgCQgEgDAAgFIAAhRQAAgFAEgDQACgDACAAIAAgDQAAgFAEgEQAEgDAFAAIAOAAQAFAAAEADQADAEAAAFIAAADQACABACACQADADAAAFIAAAAAAljQIAAgOIgOAAIAAAOIgJAAIAABRIAJAAIAABzIgIAAIAAAPIgggBIAAgPIgHAAIAAhzIAHAAIAAhQIgHAAIAAgPIgOAAIAAAPIgJAAIAABQIAJAAIAABzIgIAAIAAAPIgIAAIAAAaQAWgIAaAAQADAAADABQAAgBAAABIAAAAQAAgBAAABIAAAAQAAgBABABQACgBADAAQAZAAAWAHIAAgYIgIAAIAAgPIgIAAIAAhzIAIAAIAAhRIgIAAABXBKIAAgPQgEgDgEgDQgfgVgqAAQgDAAgDABQAAgBAAABQAAgBAAABQgCgBgEAAQgqAAgeAVQgEADgEADIAAAPIgiAXIAAAWIhyBKIAAAPIBygzIAAABIBAAAIgSAmIAAAcICVAAIAAgcIgRgmIA/AAIAAgBIByAzIAAgPIhyhKIAAgWIgigX").cp();
	this.shape_154.setTransform(0.4,23.6);

	this.addChild(this.shape_154,this.shape_153,this.shape_152,this.shape_151,this.shape_150,this.shape_149,this.shape_148,this.shape_147,this.shape_146,this.shape_145,this.shape_144,this.shape_143,this.shape_142,this.shape_141,this.shape_140,this.shape_139,this.shape_138,this.shape_137,this.shape_136,this.shape_135);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-24.2,0,49.4,47.3);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;